const SUBJECTS_DATA = [
  { id:'s_ce_BES01', code:'BES01', name:'Engineering Economics', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_BES02', code:'BES02', name:'Engineering Management', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_ce_BES04', code:'BES04', name:'Technopreneuship 101', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s5', code:'CE101', name:'Engineering Mechanics', dept:'ce', units:3, sem:'1st', active:true },
  { id:'s_ce_CHM01A', code:'CHM01A', name:'Chemistry for Engineers', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CHM01AL', code:'CHM01AL', name:'Chemistry for Engineers (Lab)', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE00', code:'CVE00', name:'Civil Engineering Orientation', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_ce_CVE01', code:'CVE01', name:'Engineering Drawings and Plans', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE05', code:'CVE05', name:'Structural Theory 1 (Lec)', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVE05L', code:'CVE05L', name:'Structural 1 (Lab)', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE06', code:'CVE06', name:'Highway and railroad Engineering', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVE07', code:'CVE07', name:'HYDRAULICS (LEC)', dept:'ce', units:4, sem:'catalog', active:true },
  { id:'s_ce_CVE07L', code:'CVE07L', name:'HYDRAULICS (LAB)', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE08', code:'CVE08', name:'Numerical Solutions to CE Problems (lec)', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_ce_CVE08L', code:'CVE08L', name:'Numerical Solutions to Ce Problems (lab)', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE09', code:'CVE09', name:'Construction Materials &Testing (lec)', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_ce_CVE09L', code:'CVE09L', name:'Construction Materials & Testing (lab)', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE10', code:'CVE10', name:'Hydrology', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_ce_CVE11', code:'CVE11', name:'Structural Theory 2 (lec)', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_ce_CVE11_L', code:'CVE11.L', name:'Structural Theory 2 (lab)', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE12', code:'CVE12', name:'Building System Design (lec)', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_ce_CVE12L', code:'CVE12L', name:'Building Systeen Design (lab)', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE13L', code:'CVE13L', name:'Principles of Steel & Timber Design (lab)', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE14', code:'CVE14', name:'Principles of Reinforced Concrete/Prestressed Concrete Design (Lec)', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVE14L', code:'CVE14L', name:'Principles of Reinforced Concrete/Prestressed Concrete Design (Lab)', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE15', code:'CVE15', name:'Construction Methods & Project Management lec', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVE16', code:'CVE16', name:'Principles of Transportation Engineering', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVE17', code:'CVE17', name:'CE Project 1', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE17L', code:'CVE17L', name:'CE Project 1 (Lab)', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE18', code:'CVE18', name:'Geotechnical Engineering 1 (Soil Mechnics)', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVE18L', code:'CVE18L', name:'Geotechnical Engineering 1 (Soil Mechanics) Lab', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE19', code:'CVE19', name:'CE Laws, Ethics and Contracts', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_ce_CVE20', code:'CVE20', name:'Quantity Surveying', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE20L', code:'CVE20L', name:'Quantity Surveying Lab', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE21', code:'CVE21', name:'CE Project 2', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE21L', code:'CVE21L', name:'CE Project 2 Lab', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE22', code:'CVE22', name:'Integratvie Course for CE', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVS01', code:'CVS01', name:'Professional Course-Specialized 1', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVS02', code:'CVS02', name:'Professional Course-Specialized 2', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVS03', code:'CVS03', name:'Professional Course-Specialized 3', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVS04', code:'CVS04', name:'Professional Course-Specialized 4', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVS05', code:'CVS05', name:'Professional Course-Specialized 5', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_EEN01A', code:'EEN01A', name:'Basic Electrical Engineering', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_GEC01', code:'GEC01', name:'The LIfe and the Works of Rizal', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_GEC03', code:'GEC03', name:'Readings in the Philippine History', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_GEC04', code:'GEC04', name:'The Contemporary World', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_GEC05', code:'GEC05', name:'Mathematics in the Modern World', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_GEC06', code:'GEC06', name:'Purposive Communication', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_GEC07', code:'GEC07', name:'Art Appreciation', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_GEC08', code:'GEC08', name:'Science, Technology and Society', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_GEC09', code:'GEC09', name:'Ethics', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_GEC10', code:'GEC10', name:'Kontekswalisadong Komunuikasyon sa Filipino', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_GEC11', code:'GEC11', name:'Filipino sa ibat ibang Disiplina', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_MAT04', code:'MAT04', name:'Calculus 1 (Differential Calculus)', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_MAT05', code:'MAT05', name:'Calculus 2 (Integral Calculus)', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_MAT07', code:'MAT07', name:'Differential Equations', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_MAT08', code:'MAT08', name:'Engineering Data Analysis', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_MCE01a', code:'MCE01a', name:'Basic Mechanical Engineering', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_MEC01', code:'MEC01', name:'Statics of RIgid Bodies', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_MEC02', code:'MEC02', name:'Dynamics of Rigid Bodies', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_ce_MEC03', code:'MEC03', name:'Mechanics of Deformable Bodies', dept:'ce', units:4, sem:'catalog', active:true },
  { id:'s_ce_NSC01', code:'NSC01', name:'Environmental Science', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_NST01', code:'NST01', name:'ROTC', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_NST02', code:'NST02', name:'ROTC 2', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_OJT', code:'OJT', name:'On-the-Job Training', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_PEO03', code:'PEO03', name:'Individual/Dual Sports', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_ce_PEO04', code:'PEO04', name:'Team Sports and Games', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_cpe_BES01', code:'BES01', name:'Engineering Economics', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_BSE04', code:'BSE04', name:'Technopreneurship 101', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CHM01a', code:'CHM01a', name:'Chemistry for Engineers', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CHM01aL', code:'CHM01aL', name:'Chemistry for Engineers (Lab)', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_COE01', code:'COE01', name:'Computer Engineering as a Discipline', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE02', code:'CPE02', name:'Programming and Logic Design', dept:'cpe', units:2, sem:'catalog', active:true },
  { id:'s_cpe_CPE03', code:'CPE03', name:'Database Management System', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE04', code:'CPE04', name:'Numerical Methods', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE05', code:'CPE05', name:'Object-Oriented Programming', dept:'cpe', units:2, sem:'catalog', active:true },
  { id:'s_cpe_CPE06', code:'CPE06', name:'On-Line Technologies', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE07', code:'CPE07', name:'Logic Circuits and Design', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE07L', code:'CPE07L', name:'Logic Circuits and Design (Lab)', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE08', code:'CPE08', name:'Computer Engineering Drafting & Design', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE09', code:'CPE09', name:'Introduction to HDL', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE10', code:'CPE10', name:'Fundamentals of Mixed Signals & Sensors', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE11', code:'CPE11', name:'Feedback and Control Systems', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE12', code:'CPE12', name:'Data and Digital Communications', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE13', code:'CPE13', name:'Data Structure and Algorithms', dept:'cpe', units:2, sem:'catalog', active:true },
  { id:'s_cpe_CPE14', code:'CPE14', name:'Basic Occupational Health and Safety', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE15', code:'CPE15', name:'Cognate/Proffesional Couse 1', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE16', code:'CPE16', name:'Computer Networks & Security', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE16L', code:'CPE16L', name:'Computer Networks & Security (Lab)', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE17', code:'CPE17', name:'Operating Systems', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE18', code:'CPE18', name:'Software Design', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE18L', code:'CPE18L', name:'Software Design (Lab)', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE19', code:'CPE19', name:'Microprocessors', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE19L', code:'CPE19L', name:'Microprocessors (Lab)', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE20', code:'CPE20', name:'Methods and Research', dept:'cpe', units:2, sem:'catalog', active:true },
  { id:'s_cpe_CPE21', code:'CPE21', name:'Cognate/Professional Course 2', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE22', code:'CPE22', name:'Digital Signal Processing', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE22L', code:'CPE22L', name:'Digital Signal Processing (Lba)', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE23', code:'CPE23', name:'Computer Architecture & Organization', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE23L', code:'CPE23L', name:'Computer Architecture & Orgranization (Lab)', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE24', code:'CPE24', name:'Embedded Systems', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE24L', code:'CPE24L', name:'Embedded Systems (Lab)', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE25', code:'CPE25', name:'CpE Practice and Design 1', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE26', code:'CPE26', name:'CpE Laws and Professional Practice', dept:'cpe', units:2, sem:'catalog', active:true },
  { id:'s_cpe_CPE27', code:'CPE27', name:'Emerging Technologies in CpE', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE28', code:'CPE28', name:'Cognate/Professional Course 3', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE29', code:'CPE29', name:'Seminars and Field Trips', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE30', code:'CPE30', name:'CpE Practice and Design 2', dept:'cpe', units:2, sem:'catalog', active:true },
  { id:'s8', code:'CPE101', name:'Computer Architecture', dept:'cpe', units:3, sem:'1st', active:true },
  { id:'s9', code:'CPE102', name:'Data Structures', dept:'cpe', units:3, sem:'1st', active:true },
  { id:'s_cpe_ECE01', code:'ECE01', name:'Fundamentals of Electronic Circuits', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_ECE01L', code:'ECE01L', name:'Fundamentals of Electronic Circuits (Lab)', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_GEC02', code:'GEC02', name:'Understanding the Self', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_GEC03', code:'GEC03', name:'Readings in Philippine History', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_GEC04', code:'GEC04', name:'The Contemporary World', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_GEC05', code:'GEC05', name:'Mathematics in the Modern World', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_GEC07', code:'GEC07', name:'Art Appreciation', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_GEC08', code:'GEC08', name:'Science, Technology and Society', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_GEC10', code:'GEC10', name:'Kontekswalisadong Komunikasyon sa Filipino', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_GEC13', code:'GEC13', name:'Literature of the Philippines', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_MAT04', code:'MAT04', name:'Calculus 1 (Differential)', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_MAT08', code:'MAT08', name:'Engineering Data Analysis', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_NST01', code:'NST01', name:'National Service Training Program 1', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_NST02', code:'NST02', name:'National Service Training Program', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_OJT', code:'OJT', name:'On-The-Job Training (240hrs)', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_PEO01', code:'PEO01', name:'Physical Fitness', dept:'cpe', units:2, sem:'catalog', active:true },
  { id:'s_cpe_PEO02', code:'PEO02', name:'Rythmic Activities', dept:'cpe', units:2, sem:'catalog', active:true },
  { id:'s_cpe_PEO03', code:'PEO03', name:'Individual/Dual Games/Sports', dept:'cpe', units:2, sem:'catalog', active:true },
  { id:'s_cpe_PEO04', code:'PEO04', name:'Team Sports/Games', dept:'cpe', units:2, sem:'catalog', active:true },
  { id:'s_ece_BES01', code:'BES01', name:'Engineering Economics', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_BES02a', code:'BES02a', name:'Engineering Management', dept:'ece', units:2, sem:'catalog', active:true },
  { id:'s_ece_BES03b', code:'BES03b', name:'Material Science and Engineering', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_BES04', code:'BES04', name:'Technopreneurship 101', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_CAD01', code:'CAD01', name:'Computer Aided Drafting', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_CHM01a', code:'CHM01a', name:'Chemistry for Engineers', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_CHM01aL', code:'CHM01aL', name:'Chemistry for Engineers Lab', dept:'ece', units:1, sem:'catalog', active:true },
  { id:'s_ece_ECE00', code:'ECE00', name:'ECE Laws, Contracts, Ethics, Standards & Safety', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE02', code:'ECE02', name:'Electronics 2: Electronic Circuit Analysis & Design', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE02L', code:'ECE02L', name:'Electronics 2: Electronic Circuit Analysis & Design Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE03', code:'ECE03', name:'Electromagnetics 3: Electronic System & Design', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE03L', code:'ECE03L', name:'Electromagnetics 3: Electronic System & Design Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE04', code:'ECE04', name:'Signals, Spectra & Signal Processing', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE04L', code:'ECE04L', name:'Signals, Spectra & Signal Processing Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE05', code:'ECE05', name:'Communications 1: Priniciples of Communication System', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE05L', code:'ECE05L', name:'Communications 1: Priniciples of Communication System Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE06', code:'ECE06', name:'Communications 2: Modulation & Coding Techniques', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE06L', code:'ECE06L', name:'Communications 2: Modulation & Coding Techniques Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE07', code:'ECE07', name:'Communication 3: Transmission Media & Antenna System', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE07L', code:'ECE07L', name:'Communication 3: Transmission Media & Antenna System Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE08', code:'ECE08', name:'Communications 4: Data Communications', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE08L', code:'ECE08L', name:'Communications 4: Data Communications Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE09', code:'ECE09', name:'Digital Electronics 1: Logic Circuits & Switching Theory', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE09L', code:'ECE09L', name:'Digital Electronics 1: Logic Circuits & Switching Theory Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE10', code:'ECE10', name:'Digital Electronics 2: Microprocessor & Microcontroller Systems & Design', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE10L', code:'ECE10L', name:'Digital Electronics 2: Microprocessor & Microcontroller Systems & Design Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE11', code:'ECE11', name:'Feedback and Control Systems', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE11L', code:'ECE11L', name:'Feedback and Control Systems Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE12', code:'ECE12', name:'Methods of Research', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE13', code:'ECE13', name:'Design 1 - Capstone Project 1', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE14', code:'ECE14', name:'Design 2 - Capstone Project 2', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE15', code:'ECE15', name:'Seminars / Colloqium', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE16', code:'ECE16', name:'Integrative Course for ECE', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s7', code:'ECE101', name:'Electronics 1', dept:'ece', units:3, sem:'1st', active:true },
  { id:'s_ece_ECM02', code:'ECM02', name:'Advanced Engineering Mathematics for ECE', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECM02L', code:'ECM02L', name:'Advanced Engineering Mathematics for ECE Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECM03', code:'ECM03', name:'Electromagnetics', dept:'ece', units:4, sem:'catalog', active:true },
  { id:'s_ece_EEC01', code:'EEC01', name:'ECE Elective 1', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_EEC01L', code:'EEC01L', name:'ECE Elective 1 Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_EEC02', code:'EEC02', name:'Elective 2', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_EEC03', code:'EEC03', name:'Elective 3', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_EEC03L', code:'EEC03L', name:'Elective 3 Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_EEC04', code:'EEC04', name:'Elective 4', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_EEC04L', code:'EEC04L', name:'Elective 4 Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_EEC020L', code:'EEC020L', name:'Elective 2 Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_EEN02', code:'EEN02', name:'Circuits 2', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_EEN02L', code:'EEN02L', name:'Circuits 2 Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC01', code:'GEC01', name:'Life & Works of Rizal', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC02', code:'GEC02', name:'Understanding the Self', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC03', code:'GEC03', name:'Readings in Philippine HIstory', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC04', code:'GEC04', name:'The Contemporary World', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC05', code:'GEC05', name:'Mathematics in the Modern World', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC06', code:'GEC06', name:'Purposive Communication', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC07', code:'GEC07', name:'Art Appreciation', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC08', code:'GEC08', name:'Science, Technology and Society', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC09', code:'GEC09', name:'Ethics', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC10', code:'GEC10', name:'Kontekswalisadong Komunikasyon sa Filipino', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC11', code:'GEC11', name:'Filipino sa Iba\'t Ibang Disiplina', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC13', code:'GEC13', name:'Literature of the Philippines', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_MAT04', code:'MAT04', name:'Calculus 1 (Differential Calculus)', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_MAT05', code:'MAT05', name:'Calculus 2 (Integral)', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_NST01', code:'NST01', name:'National Service Training Program 1', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_OJT', code:'OJT', name:'On the Job Training / Electronics Engineering Immersion', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_PEO01', code:'PEO01', name:'Physical Fitness', dept:'ece', units:2, sem:'catalog', active:true },
  { id:'s_ece_PEO03', code:'PEO03', name:'Individual/Dual Sports', dept:'ece', units:2, sem:'catalog', active:true },
  { id:'s_ece_PEO04', code:'PEO04', name:'Team Sports / Games', dept:'ece', units:2, sem:'catalog', active:true },
  { id:'s_ee_BES01', code:'BES01', name:'Engineering Economics', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_BES04', code:'BES04', name:'Technopreneurship 101', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_CHM01', code:'CHM01', name:'Chemistry for Engineers', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_CHM01aL', code:'CHM01aL', name:'Chemistry for Engineers Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_COE01', code:'COE01', name:'Engineering Orientation', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_ECE01a', code:'ECE01a', name:'Electronic Circuits, Devices & Analysis', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_ECE01aL', code:'ECE01aL', name:'Electronic Circuits, Devices & Analysis Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s3', code:'EEN01', name:'Basic Electrical Engineering', dept:'ee', units:3, sem:'1st', active:true },
  { id:'s4', code:'EEN01L', name:'Basic EE Laboratory', dept:'ee', units:1, sem:'1st', active:true },
  { id:'s_ee_EEN02', code:'EEN02', name:'Electrical Circuits 2', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_EEN02L', code:'EEN02L', name:'Electrical Circuits 2 Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN03', code:'EEN03', name:'EE Laws, Codes & Professional Ethics', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN04', code:'EEN04', name:'Engineering Math for EE', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_EEN05', code:'EEN05', name:'Engineering Electromagnetics', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN06', code:'EEN06', name:'Basic Occupational Safety and Health', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_EEN07', code:'EEN07', name:'Fundamentals of Electronic Communication', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_EEN08', code:'EEN08', name:'Numerical Methods and Analysis', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN08L', code:'EEN08L', name:'Numerical Methods and Analysis Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN09', code:'EEN09', name:'Logic Circuits & Switching Theory', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN10', code:'EEN10', name:'Electrical Machines 1', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN11', code:'EEN11', name:'Industrial Electronics', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_EEN11L', code:'EEN11L', name:'Industrial Electronics Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN12', code:'EEN12', name:'Electrical Standards & Practices', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN13', code:'EEN13', name:'Electrical Devices & Apparatus', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN13L', code:'EEN13L', name:'Electrical Devices & Apparatus Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN14', code:'EEN14', name:'Feedback Control System', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN15', code:'EEN15', name:'Microprocessor System', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN16', code:'EEN16', name:'Electrical Machines 2', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_EEN16L', code:'EEN16L', name:'Electrical Machine 2 Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN17', code:'EEN17', name:'Management of Engineering Projects', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN18', code:'EEN18', name:'Material Science & Engineering', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN19', code:'EEN19', name:'Electrical System & Illumination Engineering Design', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_EEN19L', code:'EEN19L', name:'Electrical System & Illumination Engineering Design Lab', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN20', code:'EEN20', name:'EE Elective 1', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN20L', code:'EEN20L', name:'EE Elective 1 Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN21', code:'EEN21', name:'Instrumentation and Control', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN21L', code:'EEN21L', name:'Instrumentation and Control Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN22', code:'EEN22', name:'Power System Analysis', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_EEN22L', code:'EEN22L', name:'Power System Analysis Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN23', code:'EEN23', name:'Elective 2', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN23L', code:'EEN23L', name:'Elective 2 Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN24', code:'EEN24', name:'Fundamentals of Powerplant Engineering Design', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN25', code:'EEN25', name:'Distribution System & Substation Design', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN25L', code:'EEN25L', name:'Distribution System & Substation Design Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN26', code:'EEN26', name:'Integrative Course for Electrical Engineering', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_EEN27', code:'EEN27', name:'Seminars / Colloquia', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EET01', code:'EET01', name:'Electrical Engineering Technology 1', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EET02', code:'EET02', name:'Electrial Engineering Technology 2', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_GEC01', code:'GEC01', name:'Life and Works of Rizal', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_GEC02', code:'GEC02', name:'Understanding the Self', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_GEC03', code:'GEC03', name:'Reading in Philippine History', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_GEC04', code:'GEC04', name:'The Contemporary World', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_GEC05', code:'GEC05', name:'Mathematics in the Modern World', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_GEC07', code:'GEC07', name:'Art Appreciation', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_GEC08', code:'GEC08', name:'Science, Technology & Society', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_GEC09', code:'GEC09', name:'Ethics', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_GEC10', code:'GEC10', name:'Kontekswalisadong Komunikasyon sa Filipino', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_GEC11', code:'GEC11', name:'Filipino sa Iba\'t Ibang Disiplina', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_GEC13', code:'GEC13', name:'Literature of the Philippine History', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_MAT01', code:'MAT01', name:'Calculus 1 (Differential)', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_MCE01a', code:'MCE01a', name:'Basic Thermodynamics', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_MEC03a', code:'MEC03a', name:'Fundamentals of Deformable Bodies', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_NST01', code:'NST01', name:'National Service Training Program 1', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_OJT', code:'OJT', name:'On the Job Training / Electrical Engineering Immersion', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_PEO01', code:'PEO01', name:'Physical Fitness', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_PEO02', code:'PEO02', name:'Rhytmic Activities', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_PEO03', code:'PEO03', name:'Individual / Dual Games Sports', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_PEO04', code:'PEO04', name:'Team Sports / Games', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_RES01a', code:'RES01a', name:'Research Methods', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_RES02', code:'RES02', name:'Research Project / Capstone Design', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ie_AEC02', code:'AEC02', name:'Principles of Economics', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_AEC04', code:'AEC04', name:'Financial Accounting', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_AEC05', code:'AEC05', name:'Managerial Accounting', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_BES01', code:'BES01', name:'Engineering Economics', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_BES04', code:'BES04', name:'Technopreneurship 101', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_BES05', code:'BES05', name:'Basic Occupational Safety and Health', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_CAD01', code:'CAD01', name:'Computer Aided Drafting', dept:'ie', units:1, sem:'catalog', active:true },
  { id:'s_ie_CHM01a', code:'CHM01a', name:'Chemistry for Engineers', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_CHM01aL', code:'CHM01aL', name:'Chemistry for Engineers (Lab)', dept:'ie', units:1, sem:'catalog', active:true },
  { id:'s_ie_EEN01a', code:'EEN01a', name:'Fundamentals of Electrical Circuits', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_GEC01', code:'GEC01', name:'The Life and the Works of Rizal', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_GEC02', code:'GEC02', name:'Understanding the Self', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_GEC03', code:'GEC03', name:'Redings in the Philippine History', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_GEC05', code:'GEC05', name:'Mathermatics in the Modern World', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_GEC07', code:'GEC07', name:'Art Appreciation', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_GEC08', code:'GEC08', name:'Science,Technology and Society', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_GEC09', code:'GEC09', name:'Ethics', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_GEC10', code:'GEC10', name:'Kontekswalisadong Komunikasyon sa Filipino', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s1', code:'IE101', name:'Engineering Management', dept:'ie', units:3, sem:'1st', active:true },
  { id:'s2', code:'IE102', name:'Operations Research', dept:'ie', units:3, sem:'1st', active:true },
  { id:'s_ie_IEE01', code:'IEE01', name:'Industrial Engineering Elective 1', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEE2', code:'IEE2', name:'IE Elective 2', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEE03', code:'IEE03', name:'IE Elective 3', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEN01', code:'IEN01', name:'Statistical Analysis for IE 1', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEN04', code:'IEN04', name:'Industrial Organization & Managment', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEN05', code:'IEN05', name:'Advanced Mathematics for IE', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEN06', code:'IEN06', name:'Work Study and Measurement Lec', dept:'ie', units:2, sem:'catalog', active:true },
  { id:'s_ie_IEN06L', code:'IEN06L', name:'Work Study and Measurement Lab', dept:'ie', units:1, sem:'catalog', active:true },
  { id:'s_ie_IEN07', code:'IEN07', name:'Operations Rerearch 1', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEN08', code:'IEN08', name:'Quality Management System', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEN09', code:'IEN09', name:'Ergonomics 1 Lec', dept:'ie', units:2, sem:'catalog', active:true },
  { id:'s_ie_IEN09L', code:'IEN09L', name:'Ergonomics 1 Lab', dept:'ie', units:1, sem:'catalog', active:true },
  { id:'s_ie_IEN10', code:'IEN10', name:'Operations Research 2', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEN11', code:'IEN11', name:'Operations Management Lec', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEN12', code:'IEN12', name:'Ergonomics 2 Lec', dept:'ie', units:2, sem:'catalog', active:true },
  { id:'s_ie_IEN12L', code:'IEN12L', name:'Ergonomics 2 Lab', dept:'ie', units:1, sem:'catalog', active:true },
  { id:'s_ie_IEN13', code:'IEN13', name:'Industry Computer Application', dept:'ie', units:1, sem:'catalog', active:true },
  { id:'s_ie_IEN13L', code:'IEN13L', name:'Industry Computer Application Lab', dept:'ie', units:2, sem:'catalog', active:true },
  { id:'s_ie_IEN14', code:'IEN14', name:'Project Feasibility', dept:'ie', units:2, sem:'catalog', active:true },
  { id:'s_ie_IEN14L', code:'IEN14L', name:'Project Feasibility Lab', dept:'ie', units:1, sem:'catalog', active:true },
  { id:'s_ie_IEN15', code:'IEN15', name:'Supply Chain Management', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEN16', code:'IEN16', name:'Information Systems', dept:'ie', units:2, sem:'catalog', active:true },
  { id:'s_ie_IEN16L', code:'IEN16L', name:'Information Systems Lab', dept:'ie', units:1, sem:'catalog', active:true },
  { id:'s_ie_IEN17', code:'IEN17', name:'Systems Engineering', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEN18', code:'IEN18', name:'IE Capstone Project Lec', dept:'ie', units:1, sem:'catalog', active:true },
  { id:'s_ie_IEN18L', code:'IEN18L', name:'IE Capstone Project Lab', dept:'ie', units:2, sem:'catalog', active:true },
  { id:'s_ie_IEN19', code:'IEN19', name:'IE Industry Immersion (240 Hours)', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_INE03L', code:'INE03L', name:'Industrial Materials and Processes Lab', dept:'ie', units:1, sem:'catalog', active:true },
  { id:'s_ie_MAT04', code:'MAT04', name:'Calculus 1 (Differential Calculus)', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_MAT07', code:'MAT07', name:'Differential Equations', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_MEC00', code:'MEC00', name:'Engineering Mechanics', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_MECE01', code:'MECE01', name:'Basic Thermodynamics', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_NSC01', code:'NSC01', name:'Environmental Science', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_PEO01', code:'PEO01', name:'Physical Fitness', dept:'ie', units:2, sem:'catalog', active:true },
  { id:'s_ie_PEO03', code:'PEO03', name:'Individual/ Dual Sports', dept:'ie', units:2, sem:'catalog', active:true },
  { id:'s_ie_PEO04', code:'PEO04', name:'Team Sports and Games', dept:'ie', units:2, sem:'catalog', active:true },
  { id:'s_ie_PHY03', code:'PHY03', name:'Physics for Engineers (Calculus Based)', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_me_BES01a', code:'BES01a', name:'Engineering Economics', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_BES02a', code:'BES02a', name:'Engineering Management', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_BES04', code:'BES04', name:'Technopreneurship 101', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_CHM01a', code:'CHM01a', name:'Chemistry for Engineers', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_CHM01aL', code:'CHM01aL', name:'Chemistry for Engineers Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_COE01', code:'COE01', name:'Mechanical Engineering Orientation', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_COM01', code:'COM01', name:'Computer Fundamental and Programming', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_COM02', code:'COM02', name:'Computer Application for ME', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_DRW01', code:'DRW01', name:'Engineering Drawing', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_ECE00', code:'ECE00', name:'Basic Electronics', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_ECE00L', code:'ECE00L', name:'Basic Electronics Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_EEN01A', code:'EEN01A', name:'Basic Electrical Engineering', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_EEN01AL', code:'EEN01AL', name:'Basic Electrical Engineering Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_GEC02', code:'GEC02', name:'Understanding the Self', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_GEC03', code:'GEC03', name:'Mathematics in the Modern World', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_GEC05', code:'GEC05', name:'Mathematics in the Modern World', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_GEC07', code:'GEC07', name:'Art Appreciation', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_GEC09', code:'GEC09', name:'Ethics', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_GEC10', code:'GEC10', name:'Kontekswalisadong Komunuikasyon sa Filipino', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_GEC11', code:'GEC11', name:'Filipino sa Iba\'t Ibang Disiplina', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_GEC13', code:'GEC13', name:'Literature of the Philippines', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MAT04', code:'MAT04', name:'Calculus 1 (Differential)', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MAT08', code:'MAT08', name:'Engineering Data and Analysis', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MAT10f', code:'MAT10f', name:'Advance Mathematics for ME', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MCE01', code:'MCE01', name:'Thermodynamics 1', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MCE02', code:'MCE02', name:'Thermodynamics 2', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MCE03', code:'MCE03', name:'Workshop, Theory and Practice', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE04', code:'MCE04', name:'Machine Shop Theory', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MCE05', code:'MCE05', name:'Machine Elements', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MCE05L', code:'MCE05L', name:'Machine Elements Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE06', code:'MCE06', name:'Heat Transfer', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MCE07', code:'MCE07', name:'Vibration Engineering', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MCE08', code:'MCE08', name:'Refrigeration System', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MCE09', code:'MCE09', name:'Fluid Machinery', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MCE10', code:'MCE10', name:'Combustion Engineering', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MCE11', code:'MCE11', name:'ME Laboratory 1', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE12', code:'MCE12', name:'Material Science and Engineering for ME', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MCE12L', code:'MCE12L', name:'Material Science and Engineering for ME Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE13', code:'MCE13', name:'DC and AC Machineris', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MCE13L', code:'MCE13L', name:'DC and AC Machineris Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE14', code:'MCE14', name:'ME Elective 1 Electro Pneumatics', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE14L', code:'MCE14L', name:'ME Elective 1 Electro Pneumatics Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE15', code:'MCE15', name:'Machine Design', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MCE17', code:'MCE17', name:'Control Engineering', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MCE17L', code:'MCE17L', name:'Control Engineering Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE18', code:'MCE18', name:'Air Conditioning and Ventilation System', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MCE19', code:'MCE19', name:'Power Plant Design with Renewable Energy', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MCE19L', code:'MCE19L', name:'Power Plant Design with Renewable Energy Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE20', code:'MCE20', name:'ME Elective 2 Mechatronics', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE20L', code:'MCE20L', name:'ME Elective 2 Mechatronics Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE21', code:'MCE21', name:'ME Laboratory 3', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MCE22', code:'MCE22', name:'Machine Design 2', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MCE22L', code:'MCE22L', name:'Machine Design 2', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE23', code:'MCE23', name:'Industrial Plant Engineering', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MCE23L', code:'MCE23L', name:'Industrial Plant Engineering Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE25', code:'MCE25', name:'Basic Occupational Safety and Health', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MCE26', code:'MCE26', name:'Integrative Course for ME', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s6', code:'ME101', name:'Thermodynamics', dept:'me', units:3, sem:'1st', active:true },
  { id:'s_me_MEC02', code:'MEC02', name:'Dynamics of Rigid Bodies', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MEC03', code:'MEC03', name:'Mechanics of Deformable Bodies', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MEC04c', code:'MEC04c', name:'Fluid Mechanics', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_OJT', code:'OJT', name:'On the Job Training / Summer', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_PATHFIT03', code:'PATHFIT03', name:'Rhythmic Activities and Sports', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_PATHFIT04', code:'PATHFIT04', name:'Recreational Activities', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_PHY03', code:'PHY03', name:'Physics for Engineers', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_PHY03L', code:'PHY03L', name:'Physics for Engineers Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_RES01', code:'RES01', name:'Methods of Research for ME', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_RES02a', code:'RES02a', name:'ME Project Study 1', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_RES02b', code:'RES02b', name:'Project Study 2', dept:'me', units:1, sem:'catalog', active:true },
];
