// data.js
// Rooms, faculty, and sections: finalized program lists (chair scheduling dropdowns).
// SUBJECTS_DATA is built from Google Sheets curriculum tabs (see scripts/build-subjects-from-sheet.mjs).
// SCHEDULES / REQUESTS below are sample data for the UI.

const DEPARTMENTS = [
  { id:'ie', code:'IE', name:'Industrial Engineering', chair:'Engr. Lynnevel R. Amparo' },
  { id:'cpe', code:'CPE', name:'Computer Engineering', chair:'Engr. Julie Ann Susa-Gili' },
  { id:'ce', code:'CE', name:'Civil Engineering', chair:'Engr. John Christopher D. Tayoto' },
  { id:'ee', code:'EE', name:'Electrical Engineering', chair:'Engr. Maurino N. Abuel' },
  { id:'me', code:'ME', name:'Mechanical Engineering', chair:'Engr. Ronnel S. Nombrefia' },
  { id:'ece', code:'ECE', name:'Electronics Engineering', chair:'Engr. Pitz Gerald G. Lagrazon' },
];

// Classrooms & labs — finalized lists per program (chair scheduling dropdowns)
const ROOMS = [
  { id:'ie_mdhp303', name:'MDHP 303', type:'classroom', dept:'ie' },
  { id:'ie_mdhp305', name:'MDHP 305', type:'classroom', dept:'ie' },
  { id:'ie_mdhp307', name:'MDHP 307', type:'classroom', dept:'ie' },
  { id:'lab_ie_a', name:'IE LAB A', type:'laboratory', dept:'ie' },
  { id:'lab_ie_b', name:'IE LAB B', type:'laboratory', dept:'ie' },
  { id:'cpe_302', name:'MDHP 302', type:'classroom', dept:'cpe' },
  { id:'cpe_101', name:'MDHP 101', type:'classroom', dept:'cpe' },
  { id:'cpe_207', name:'MDHP 207', type:'classroom', dept:'cpe' },
  { id:'lab_cpe_a', name:'CPE LAB A', type:'laboratory', dept:'cpe' },
  { id:'lab_cpe_b', name:'CPE LAB B', type:'laboratory', dept:'cpe' },
  { id:'ee_mdhp209', name:'MDHP 209', type:'classroom', dept:'ee' },
  { id:'ee_mdhp211', name:'MDHP 211', type:'classroom', dept:'ee' },
  { id:'ee_mdhp301', name:'MDHP 301', type:'classroom', dept:'ee' },
  { id:'ee_mdhp306', name:'MDHP 306', type:'classroom', dept:'ee' },
  { id:'lab_ee_a', name:'EE LAB A', type:'laboratory', dept:'ee' },
  { id:'ee_lab_b', name:'EE LAB B', type:'laboratory', dept:'ee' },
  { id:'ee_lab_c', name:'EE LAB C', type:'laboratory', dept:'ee' },
  { id:'ece_mhdp201', name:'MHDP 201', type:'classroom', dept:'ece' },
  { id:'ece_mhdp203', name:'MHDP 203', type:'classroom', dept:'ece' },
  { id:'ece_mhdp205', name:'MHDP 205', type:'classroom', dept:'ece' },
  { id:'ece_mhdp207', name:'MHDP 207', type:'classroom', dept:'ece' },
  { id:'ece_mhdp209', name:'MHDP 209', type:'classroom', dept:'ece' },
  { id:'ece_fm_lab', name:'FM LAB', type:'laboratory', dept:'ece' },
  { id:'ece_elex_lab', name:'ELEX LAB', type:'laboratory', dept:'ece' },
  { id:'ce_mdhp103', name:'MDHP 103', type:'classroom', dept:'ce' },
  { id:'ce_mdhp105', name:'MDHP 105', type:'classroom', dept:'ce' },
  { id:'ce_mdhp107', name:'MDHP 107', type:'classroom', dept:'ce' },
  { id:'ce_mdhp111', name:'MDHP 111 (LAB)', type:'laboratory', dept:'ce' },
  { id:'ce_drwng', name:'DRWNG ROOM', type:'classroom', dept:'ce' },
  { id:'me_mhdp102', name:'MHDP 102', type:'classroom', dept:'me' },
  { id:'me_mdhp108', name:'MDHP 108', type:'classroom', dept:'me' },
  { id:'me_mdhp114', name:'MDHP 114', type:'classroom', dept:'me' },
  { id:'me_mdhp_melab', name:'MDHP ME LAB', type:'laboratory', dept:'me' },
  { id:'me_new_melab', name:'NEW ME LAB', type:'laboratory', dept:'me' },
  { id:'me_draw_rm', name:'DRAWING ROOM', type:'classroom', dept:'me' },
];

// Faculty — finalized rosters per program
const PROFESSORS_DATA = [
  { id:'p_ie_1', name:'MARIA CORAZON B. ABEJO, PhD', short:'M. Abejo', dept:'ie', active:true },
  { id:'p_ie_2', name:'ENGR. LYNNEVEL R. AMPARO', short:'L. Amparo', dept:'ie', active:true },
  { id:'p_ie_3', name:'MARIA ROSSANA D. DE VELUZ, PhD', short:'M. De Veluz', dept:'ie', active:true },
  { id:'p_ie_4', name:'ENGR. MARIBELLE A. GAYTANO', short:'M. Gaytano', dept:'ie', active:true },
  { id:'p_ie_5', name:'ENGR. CRESENCIA R. JARABESE', short:'C. Jarabese', dept:'ie', active:true },
  { id:'p_ie_6', name:'ENGR. REGLELYN N. MENCHERO', short:'R. Menchero', dept:'ie', active:true },
  { id:'p_ie_7', name:'ENGR. ERNEST PAUL Y. SISON', short:'E. Sison', dept:'ie', active:true },
  { id:'p_cpe_1', name:'ENGR. MANDONNA D. CASTRO', short:'M. Castro', dept:'cpe', active:true },
  { id:'p_cpe_2', name:'ENGR. CARLA MAY C. CERIBO', short:'C. Ceribo', dept:'cpe', active:true },
  { id:'p_cpe_3', name:'ENGR. JULIE ANN S. GILI', short:'J. Gili', dept:'cpe', active:true },
  { id:'p_cpe_4', name:'RENATO R. MAALIW III, PhD', short:'R. Maaliw', dept:'cpe', active:true },
  { id:'p_cpe_5', name:'ENGR. JOHN HARVEY ALVA', short:'J. Alva', dept:'cpe', active:true },
  { id:'p_cpe_6', name:'ENGR. MARIA NIEVES D. ELARCO', short:'M. Elarco', dept:'cpe', active:true },
  { id:'p_cpe_7', name:'ENGR. JOSE YULO MANZANERO', short:'J. Manzanero', dept:'cpe', active:true },
  { id:'p_cpe_8', name:'ENGR. OMAR IRISH S. MARAVILLA', short:'O. Maravilla', dept:'cpe', active:true },
  { id:'p_cpe_9', name:'ENGR. DEAN ADRIAN L. NOMBREFIA', short:'D. Nombrefia', dept:'cpe', active:true },
  { id:'p_cpe_10', name:'ENGR. JERWIN V. OBMERGA', short:'J. Obmerga', dept:'cpe', active:true },
  { id:'p_cpe_11', name:'ENGR. LEONARD ALLEN R. PAVINO', short:'L. Pavino', dept:'cpe', active:true },
  { id:'p_ee_1', name:'ENGR. MAURINO N. ABUEL', short:'M. Abuel', dept:'ee', active:true },
  { id:'p_ee_2', name:'ENGR. AUBEE MAHUSAY-ECLEO', short:'A. Ecleo', dept:'ee', active:true },
  { id:'p_ee_3', name:'ENGR. JOHN V. ELLA', short:'J. Ella', dept:'ee', active:true },
  { id:'p_ee_4', name:'EFREN D. VILLAVERDE, PhD', short:'E. Villaverde', dept:'ee', active:true },
  { id:'p_ee_5', name:'ENGR. RIZANDY J. ARROYO', short:'R. Arroyo', dept:'ee', active:true },
  { id:'p_ee_6', name:'ENGR. MELLER P. GONZALES', short:'M. Gonzales', dept:'ee', active:true },
  { id:'p_ee_7', name:'ENGR. ROMEO O. MAROTO', short:'R. Maroto', dept:'ee', active:true },
  { id:'p_ee_8', name:'ENGR. MARCELITO P. OBLEA JR.', short:'M. Oblea', dept:'ee', active:true },
  { id:'p_ee_9', name:'ENGR. MARK DARIES Q. SARDEA', short:'M. Sardea', dept:'ee', active:true },
  { id:'p_ee_10', name:'ENGR. CONRADO E. QUINALAYO', short:'C. Quinalayo', dept:'ee', active:true },
  { id:'p_ece_1', name:'PITZ GERALD G. LAGRAZON, PhD', short:'P. Lagrazon', dept:'ece', active:true },
  { id:'p_ece_2', name:'ENGR. JOHN VISTOR ADEL T. LIWAG', short:'J. Liwag', dept:'ece', active:true },
  { id:'p_ece_3', name:'ENGR. ZOREN P. MABUNGA', short:'Z. Mabunga', dept:'ece', active:true },
  { id:'p_ece_4', name:'ENGR. MAURINE C. PANERGIO', short:'M. Panergio', dept:'ece', active:true },
  { id:'p_ece_5', name:'ENGR. RENANTE D. ABUYAN', short:'R. Abuyan', dept:'ece', active:true },
  { id:'p_ece_6', name:'ENGR. JOEL ANTHONY L. SEVILLA', short:'J. Sevilla', dept:'ece', active:true },
  { id:'p_ece_7', name:'ENGR. MARJUN C. MACRIOLA', short:'M. Macriola', dept:'ece', active:true },
  { id:'p_ece_8', name:'ENGR. ANTHONY L. REIGO', short:'A. Reigo', dept:'ece', active:true },
  { id:'p_ece_9', name:'ENGR. RALPH MONSOUR Z. DELIMA', short:'R. Delima', dept:'ece', active:true },
  { id:'p_ece_10', name:'MARIA NIEVES D. ELARCO', short:'M. Elarco', dept:'ece', active:true },
  { id:'p_ce_1', name:'ENGR. WINDA S. ELLAGA', short:'W. Ellaga', dept:'ce', active:true },
  { id:'p_ce_2', name:'ENGR. JAMAICA C. SALIENDRA', short:'J. Saliendra', dept:'ce', active:true },
  { id:'p_ce_3', name:'ENGR. JOHN CHRISTOPHER D. TAYOTO', short:'J. Tayoto', dept:'ce', active:true },
  { id:'p_ce_4', name:'AR. AIVAN BENEDICT Q. ELLA', short:'A. Ella', dept:'ce', active:true },
  { id:'p_ce_5', name:'ENGR. JANE COLEEN R. LINGATONG', short:'J. Lingatong', dept:'ce', active:true },
  { id:'p_ce_6', name:'ENGR. DELIA O. EVANGELISTA', short:'D. Evangelista', dept:'ce', active:true },
  { id:'p_ce_7', name:'ENGR. JEROME IGNACIO', short:'J. Ignacio', dept:'ce', active:true },
  { id:'p_me_1', name:'ENGR. GILBERT R. ESQUILLIO', short:'G. Esquillio', dept:'me', active:true },
  { id:'p_me_2', name:'ENGR. RONNEL S. NOMBREFIA', short:'R. Nombrefia', dept:'me', active:true },
  { id:'p_me_3', name:'ENGR. OSCAR D. VILLAVERDE', short:'O. Villaverde', dept:'me', active:true },
  { id:'p_me_4', name:'ENGR. DAN MARK C. CABRIGA', short:'D. Cabriga', dept:'me', active:true },
  { id:'p_me_5', name:'ENGR. RAMON ACE VITASA', short:'R. Vitasa', dept:'me', active:true },
  { id:'p_me_6', name:'ENGR. DONA B. BUEQUE', short:'D. Bueque', dept:'me', active:true },
  { id:'p_me_7', name:'ENGR. MAUREEN E. ROAZA', short:'M. Roaza', dept:'me', active:true },
  { id:'p_me_8', name:'ENGR. JEROME D. IGNACIO', short:'J. Ignacio', dept:'me', active:true },
];

const SUBJECTS_DATA = [
  { id:'s_ce_BES01', code:'BES01', name:'Engineering Economics', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_BES02', code:'BES02', name:'Engineering Management', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_ce_BES04', code:'BES04', name:'Technopreneuship 101', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s5', code:'CE101', name:'Engineering Mechanics', dept:'ce', units:3, sem:'1st', active:true },
  { id:'s_ce_CHM01A', code:'CHM01A', name:'Chemistry for Engineers', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CHM01AL', code:'CHM01AL', name:'Chemistry for Engineers (Lab)', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE00', code:'CVE00', name:'Civil Engineering Orientation', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_ce_CVE01', code:'CVE01', name:'Engineering Drawings and Plans', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE05', code:'CVE05', name:'Structural Theory 1 (Lec)', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVE05L', code:'CVE05L', name:'Structural 1 (Lab)', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE06', code:'CVE06', name:'Highway and railroad Engineering', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVE07', code:'CVE07', name:'HYDRAULICS (LEC)', dept:'ce', units:4, sem:'catalog', active:true },
  { id:'s_ce_CVE07L', code:'CVE07L', name:'HYDRAULICS (LAB)', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE08', code:'CVE08', name:'Numerical Solutions to CE Problems (lec)', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_ce_CVE08L', code:'CVE08L', name:'Numerical Solutions to Ce Problems (lab)', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE09', code:'CVE09', name:'Construction Materials &Testing (lec)', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_ce_CVE09L', code:'CVE09L', name:'Construction Materials & Testing (lab)', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE10', code:'CVE10', name:'Hydrology', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_ce_CVE11', code:'CVE11', name:'Structural Theory 2 (lec)', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_ce_CVE11_L', code:'CVE11.L', name:'Structural Theory 2 (lab)', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE12', code:'CVE12', name:'Building System Design (lec)', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_ce_CVE12L', code:'CVE12L', name:'Building Systeen Design (lab)', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE13L', code:'CVE13L', name:'Principles of Steel & Timber Design (lab)', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE14', code:'CVE14', name:'Principles of Reinforced Concrete/Prestressed Concrete Design (Lec)', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVE14L', code:'CVE14L', name:'Principles of Reinforced Concrete/Prestressed Concrete Design (Lab)', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE15', code:'CVE15', name:'Construction Methods & Project Management lec', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVE16', code:'CVE16', name:'Principles of Transportation Engineering', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVE17', code:'CVE17', name:'CE Project 1', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE17L', code:'CVE17L', name:'CE Project 1 (Lab)', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE18', code:'CVE18', name:'Geotechnical Engineering 1 (Soil Mechnics)', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVE18L', code:'CVE18L', name:'Geotechnical Engineering 1 (Soil Mechanics) Lab', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE19', code:'CVE19', name:'CE Laws, Ethics and Contracts', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_ce_CVE20', code:'CVE20', name:'Quantity Surveying', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE20L', code:'CVE20L', name:'Quantity Surveying Lab', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE21', code:'CVE21', name:'CE Project 2', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE21L', code:'CVE21L', name:'CE Project 2 Lab', dept:'ce', units:1, sem:'catalog', active:true },
  { id:'s_ce_CVE22', code:'CVE22', name:'Integratvie Course for CE', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVS01', code:'CVS01', name:'Professional Course-Specialized 1', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVS02', code:'CVS02', name:'Professional Course-Specialized 2', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVS03', code:'CVS03', name:'Professional Course-Specialized 3', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVS04', code:'CVS04', name:'Professional Course-Specialized 4', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_CVS05', code:'CVS05', name:'Professional Course-Specialized 5', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_EEN01A', code:'EEN01A', name:'Basic Electrical Engineering', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_GEC01', code:'GEC01', name:'The LIfe and the Works of Rizal', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_GEC03', code:'GEC03', name:'Readings in the Philippine History', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_GEC04', code:'GEC04', name:'The Contemporary World', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_GEC05', code:'GEC05', name:'Mathematics in the Modern World', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_GEC06', code:'GEC06', name:'Purposive Communication', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_GEC07', code:'GEC07', name:'Art Appreciation', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_GEC08', code:'GEC08', name:'Science, Technology and Society', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_GEC09', code:'GEC09', name:'Ethics', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_GEC10', code:'GEC10', name:'Kontekswalisadong Komunuikasyon sa Filipino', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_GEC11', code:'GEC11', name:'Filipino sa ibat ibang Disiplina', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_MAT04', code:'MAT04', name:'Calculus 1 (Differential Calculus)', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_MAT05', code:'MAT05', name:'Calculus 2 (Integral Calculus)', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_MAT07', code:'MAT07', name:'Differential Equations', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_MAT08', code:'MAT08', name:'Engineering Data Analysis', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_MCE01a', code:'MCE01a', name:'Basic Mechanical Engineering', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_MEC01', code:'MEC01', name:'Statics of RIgid Bodies', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_MEC02', code:'MEC02', name:'Dynamics of Rigid Bodies', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_ce_MEC03', code:'MEC03', name:'Mechanics of Deformable Bodies', dept:'ce', units:4, sem:'catalog', active:true },
  { id:'s_ce_NSC01', code:'NSC01', name:'Environmental Science', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_NST01', code:'NST01', name:'ROTC', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_NST02', code:'NST02', name:'ROTC 2', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_OJT', code:'OJT', name:'On-the-Job Training', dept:'ce', units:3, sem:'catalog', active:true },
  { id:'s_ce_PEO03', code:'PEO03', name:'Individual/Dual Sports', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_ce_PEO04', code:'PEO04', name:'Team Sports and Games', dept:'ce', units:2, sem:'catalog', active:true },
  { id:'s_cpe_BES01', code:'BES01', name:'Engineering Economics', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_BSE04', code:'BSE04', name:'Technopreneurship 101', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CHM01a', code:'CHM01a', name:'Chemistry for Engineers', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CHM01aL', code:'CHM01aL', name:'Chemistry for Engineers (Lab)', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_COE01', code:'COE01', name:'Computer Engineering as a Discipline', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE02', code:'CPE02', name:'Programming and Logic Design', dept:'cpe', units:2, sem:'catalog', active:true },
  { id:'s_cpe_CPE03', code:'CPE03', name:'Database Management System', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE04', code:'CPE04', name:'Numerical Methods', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE05', code:'CPE05', name:'Object-Oriented Programming', dept:'cpe', units:2, sem:'catalog', active:true },
  { id:'s_cpe_CPE06', code:'CPE06', name:'On-Line Technologies', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE07', code:'CPE07', name:'Logic Circuits and Design', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE07L', code:'CPE07L', name:'Logic Circuits and Design (Lab)', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE08', code:'CPE08', name:'Computer Engineering Drafting & Design', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE09', code:'CPE09', name:'Introduction to HDL', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE10', code:'CPE10', name:'Fundamentals of Mixed Signals & Sensors', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE11', code:'CPE11', name:'Feedback and Control Systems', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE12', code:'CPE12', name:'Data and Digital Communications', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE13', code:'CPE13', name:'Data Structure and Algorithms', dept:'cpe', units:2, sem:'catalog', active:true },
  { id:'s_cpe_CPE14', code:'CPE14', name:'Basic Occupational Health and Safety', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE15', code:'CPE15', name:'Cognate/Proffesional Couse 1', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE16', code:'CPE16', name:'Computer Networks & Security', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE16L', code:'CPE16L', name:'Computer Networks & Security (Lab)', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE17', code:'CPE17', name:'Operating Systems', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE18', code:'CPE18', name:'Software Design', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE18L', code:'CPE18L', name:'Software Design (Lab)', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE19', code:'CPE19', name:'Microprocessors', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE19L', code:'CPE19L', name:'Microprocessors (Lab)', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE20', code:'CPE20', name:'Methods and Research', dept:'cpe', units:2, sem:'catalog', active:true },
  { id:'s_cpe_CPE21', code:'CPE21', name:'Cognate/Professional Course 2', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE22', code:'CPE22', name:'Digital Signal Processing', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE22L', code:'CPE22L', name:'Digital Signal Processing (Lba)', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE23', code:'CPE23', name:'Computer Architecture & Organization', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE23L', code:'CPE23L', name:'Computer Architecture & Orgranization (Lab)', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE24', code:'CPE24', name:'Embedded Systems', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE24L', code:'CPE24L', name:'Embedded Systems (Lab)', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE25', code:'CPE25', name:'CpE Practice and Design 1', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE26', code:'CPE26', name:'CpE Laws and Professional Practice', dept:'cpe', units:2, sem:'catalog', active:true },
  { id:'s_cpe_CPE27', code:'CPE27', name:'Emerging Technologies in CpE', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE28', code:'CPE28', name:'Cognate/Professional Course 3', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_CPE29', code:'CPE29', name:'Seminars and Field Trips', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_CPE30', code:'CPE30', name:'CpE Practice and Design 2', dept:'cpe', units:2, sem:'catalog', active:true },
  { id:'s8', code:'CPE101', name:'Computer Architecture', dept:'cpe', units:3, sem:'1st', active:true },
  { id:'s9', code:'CPE102', name:'Data Structures', dept:'cpe', units:3, sem:'1st', active:true },
  { id:'s_cpe_ECE01', code:'ECE01', name:'Fundamentals of Electronic Circuits', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_ECE01L', code:'ECE01L', name:'Fundamentals of Electronic Circuits (Lab)', dept:'cpe', units:1, sem:'catalog', active:true },
  { id:'s_cpe_GEC02', code:'GEC02', name:'Understanding the Self', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_GEC03', code:'GEC03', name:'Readings in Philippine History', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_GEC04', code:'GEC04', name:'The Contemporary World', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_GEC05', code:'GEC05', name:'Mathematics in the Modern World', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_GEC07', code:'GEC07', name:'Art Appreciation', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_GEC08', code:'GEC08', name:'Science, Technology and Society', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_GEC10', code:'GEC10', name:'Kontekswalisadong Komunikasyon sa Filipino', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_GEC13', code:'GEC13', name:'Literature of the Philippines', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_MAT04', code:'MAT04', name:'Calculus 1 (Differential)', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_MAT08', code:'MAT08', name:'Engineering Data Analysis', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_NST01', code:'NST01', name:'National Service Training Program 1', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_NST02', code:'NST02', name:'National Service Training Program', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_OJT', code:'OJT', name:'On-The-Job Training (240hrs)', dept:'cpe', units:3, sem:'catalog', active:true },
  { id:'s_cpe_PEO01', code:'PEO01', name:'Physical Fitness', dept:'cpe', units:2, sem:'catalog', active:true },
  { id:'s_cpe_PEO02', code:'PEO02', name:'Rythmic Activities', dept:'cpe', units:2, sem:'catalog', active:true },
  { id:'s_cpe_PEO03', code:'PEO03', name:'Individual/Dual Games/Sports', dept:'cpe', units:2, sem:'catalog', active:true },
  { id:'s_cpe_PEO04', code:'PEO04', name:'Team Sports/Games', dept:'cpe', units:2, sem:'catalog', active:true },
  { id:'s_ece_BES01', code:'BES01', name:'Engineering Economics', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_BES02a', code:'BES02a', name:'Engineering Management', dept:'ece', units:2, sem:'catalog', active:true },
  { id:'s_ece_BES03b', code:'BES03b', name:'Material Science and Engineering', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_BES04', code:'BES04', name:'Technopreneurship 101', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_CAD01', code:'CAD01', name:'Computer Aided Drafting', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_CHM01a', code:'CHM01a', name:'Chemistry for Engineers', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_CHM01aL', code:'CHM01aL', name:'Chemistry for Engineers Lab', dept:'ece', units:1, sem:'catalog', active:true },
  { id:'s_ece_ECE00', code:'ECE00', name:'ECE Laws, Contracts, Ethics, Standards & Safety', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE02', code:'ECE02', name:'Electronics 2: Electronic Circuit Analysis & Design', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE02L', code:'ECE02L', name:'Electronics 2: Electronic Circuit Analysis & Design Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE03', code:'ECE03', name:'Electromagnetics 3: Electronic System & Design', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE03L', code:'ECE03L', name:'Electromagnetics 3: Electronic System & Design Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE04', code:'ECE04', name:'Signals, Spectra & Signal Processing', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE04L', code:'ECE04L', name:'Signals, Spectra & Signal Processing Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE05', code:'ECE05', name:'Communications 1: Priniciples of Communication System', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE05L', code:'ECE05L', name:'Communications 1: Priniciples of Communication System Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE06', code:'ECE06', name:'Communications 2: Modulation & Coding Techniques', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE06L', code:'ECE06L', name:'Communications 2: Modulation & Coding Techniques Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE07', code:'ECE07', name:'Communication 3: Transmission Media & Antenna System', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE07L', code:'ECE07L', name:'Communication 3: Transmission Media & Antenna System Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE08', code:'ECE08', name:'Communications 4: Data Communications', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE08L', code:'ECE08L', name:'Communications 4: Data Communications Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE09', code:'ECE09', name:'Digital Electronics 1: Logic Circuits & Switching Theory', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE09L', code:'ECE09L', name:'Digital Electronics 1: Logic Circuits & Switching Theory Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE10', code:'ECE10', name:'Digital Electronics 2: Microprocessor & Microcontroller Systems & Design', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE10L', code:'ECE10L', name:'Digital Electronics 2: Microprocessor & Microcontroller Systems & Design Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE11', code:'ECE11', name:'Feedback and Control Systems', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE11L', code:'ECE11L', name:'Feedback and Control Systems Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE12', code:'ECE12', name:'Methods of Research', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE13', code:'ECE13', name:'Design 1 - Capstone Project 1', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE14', code:'ECE14', name:'Design 2 - Capstone Project 2', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE15', code:'ECE15', name:'Seminars / Colloqium', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECE16', code:'ECE16', name:'Integrative Course for ECE', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s7', code:'ECE101', name:'Electronics 1', dept:'ece', units:3, sem:'1st', active:true },
  { id:'s_ece_ECM02', code:'ECM02', name:'Advanced Engineering Mathematics for ECE', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECM02L', code:'ECM02L', name:'Advanced Engineering Mathematics for ECE Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_ECM03', code:'ECM03', name:'Electromagnetics', dept:'ece', units:4, sem:'catalog', active:true },
  { id:'s_ece_EEC01', code:'EEC01', name:'ECE Elective 1', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_EEC01L', code:'EEC01L', name:'ECE Elective 1 Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_EEC02', code:'EEC02', name:'Elective 2', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_EEC03', code:'EEC03', name:'Elective 3', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_EEC03L', code:'EEC03L', name:'Elective 3 Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_EEC04', code:'EEC04', name:'Elective 4', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_EEC04L', code:'EEC04L', name:'Elective 4 Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_EEC020L', code:'EEC020L', name:'Elective 2 Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_EEN02', code:'EEN02', name:'Circuits 2', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_EEN02L', code:'EEN02L', name:'Circuits 2 Lab', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC01', code:'GEC01', name:'Life & Works of Rizal', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC02', code:'GEC02', name:'Understanding the Self', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC03', code:'GEC03', name:'Readings in Philippine HIstory', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC04', code:'GEC04', name:'The Contemporary World', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC05', code:'GEC05', name:'Mathematics in the Modern World', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC06', code:'GEC06', name:'Purposive Communication', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC07', code:'GEC07', name:'Art Appreciation', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC08', code:'GEC08', name:'Science, Technology and Society', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC09', code:'GEC09', name:'Ethics', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC10', code:'GEC10', name:'Kontekswalisadong Komunikasyon sa Filipino', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC11', code:'GEC11', name:'Filipino sa Iba\'t Ibang Disiplina', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_GEC13', code:'GEC13', name:'Literature of the Philippines', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_MAT04', code:'MAT04', name:'Calculus 1 (Differential Calculus)', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_MAT05', code:'MAT05', name:'Calculus 2 (Integral)', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_NST01', code:'NST01', name:'National Service Training Program 1', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_OJT', code:'OJT', name:'On the Job Training / Electronics Engineering Immersion', dept:'ece', units:3, sem:'catalog', active:true },
  { id:'s_ece_PEO01', code:'PEO01', name:'Physical Fitness', dept:'ece', units:2, sem:'catalog', active:true },
  { id:'s_ece_PEO03', code:'PEO03', name:'Individual/Dual Sports', dept:'ece', units:2, sem:'catalog', active:true },
  { id:'s_ece_PEO04', code:'PEO04', name:'Team Sports / Games', dept:'ece', units:2, sem:'catalog', active:true },
  { id:'s_ee_BES01', code:'BES01', name:'Engineering Economics', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_BES04', code:'BES04', name:'Technopreneurship 101', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_CHM01', code:'CHM01', name:'Chemistry for Engineers', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_CHM01aL', code:'CHM01aL', name:'Chemistry for Engineers Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_COE01', code:'COE01', name:'Engineering Orientation', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_ECE01a', code:'ECE01a', name:'Electronic Circuits, Devices & Analysis', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_ECE01aL', code:'ECE01aL', name:'Electronic Circuits, Devices & Analysis Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s3', code:'EEN01', name:'Basic Electrical Engineering', dept:'ee', units:3, sem:'1st', active:true },
  { id:'s4', code:'EEN01L', name:'Basic EE Laboratory', dept:'ee', units:1, sem:'1st', active:true },
  { id:'s_ee_EEN02', code:'EEN02', name:'Electrical Circuits 2', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_EEN02L', code:'EEN02L', name:'Electrical Circuits 2 Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN03', code:'EEN03', name:'EE Laws, Codes & Professional Ethics', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN04', code:'EEN04', name:'Engineering Math for EE', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_EEN05', code:'EEN05', name:'Engineering Electromagnetics', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN06', code:'EEN06', name:'Basic Occupational Safety and Health', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_EEN07', code:'EEN07', name:'Fundamentals of Electronic Communication', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_EEN08', code:'EEN08', name:'Numerical Methods and Analysis', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN08L', code:'EEN08L', name:'Numerical Methods and Analysis Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN09', code:'EEN09', name:'Logic Circuits & Switching Theory', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN10', code:'EEN10', name:'Electrical Machines 1', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN11', code:'EEN11', name:'Industrial Electronics', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_EEN11L', code:'EEN11L', name:'Industrial Electronics Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN12', code:'EEN12', name:'Electrical Standards & Practices', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN13', code:'EEN13', name:'Electrical Devices & Apparatus', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN13L', code:'EEN13L', name:'Electrical Devices & Apparatus Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN14', code:'EEN14', name:'Feedback Control System', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN15', code:'EEN15', name:'Microprocessor System', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN16', code:'EEN16', name:'Electrical Machines 2', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_EEN16L', code:'EEN16L', name:'Electrical Machine 2 Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN17', code:'EEN17', name:'Management of Engineering Projects', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN18', code:'EEN18', name:'Material Science & Engineering', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN19', code:'EEN19', name:'Electrical System & Illumination Engineering Design', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_EEN19L', code:'EEN19L', name:'Electrical System & Illumination Engineering Design Lab', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN20', code:'EEN20', name:'EE Elective 1', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN20L', code:'EEN20L', name:'EE Elective 1 Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN21', code:'EEN21', name:'Instrumentation and Control', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN21L', code:'EEN21L', name:'Instrumentation and Control Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN22', code:'EEN22', name:'Power System Analysis', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_EEN22L', code:'EEN22L', name:'Power System Analysis Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN23', code:'EEN23', name:'Elective 2', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN23L', code:'EEN23L', name:'Elective 2 Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN24', code:'EEN24', name:'Fundamentals of Powerplant Engineering Design', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN25', code:'EEN25', name:'Distribution System & Substation Design', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_EEN25L', code:'EEN25L', name:'Distribution System & Substation Design Lab', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EEN26', code:'EEN26', name:'Integrative Course for Electrical Engineering', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_EEN27', code:'EEN27', name:'Seminars / Colloquia', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EET01', code:'EET01', name:'Electrical Engineering Technology 1', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_EET02', code:'EET02', name:'Electrial Engineering Technology 2', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_GEC01', code:'GEC01', name:'Life and Works of Rizal', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_GEC02', code:'GEC02', name:'Understanding the Self', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_GEC03', code:'GEC03', name:'Reading in Philippine History', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_GEC04', code:'GEC04', name:'The Contemporary World', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_GEC05', code:'GEC05', name:'Mathematics in the Modern World', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_GEC07', code:'GEC07', name:'Art Appreciation', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_GEC08', code:'GEC08', name:'Science, Technology & Society', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_GEC09', code:'GEC09', name:'Ethics', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_GEC10', code:'GEC10', name:'Kontekswalisadong Komunikasyon sa Filipino', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_GEC11', code:'GEC11', name:'Filipino sa Iba\'t Ibang Disiplina', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_GEC13', code:'GEC13', name:'Literature of the Philippine History', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_MAT01', code:'MAT01', name:'Calculus 1 (Differential)', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_MCE01a', code:'MCE01a', name:'Basic Thermodynamics', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_MEC03a', code:'MEC03a', name:'Fundamentals of Deformable Bodies', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_NST01', code:'NST01', name:'National Service Training Program 1', dept:'ee', units:3, sem:'catalog', active:true },
  { id:'s_ee_OJT', code:'OJT', name:'On the Job Training / Electrical Engineering Immersion', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_PEO01', code:'PEO01', name:'Physical Fitness', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_PEO02', code:'PEO02', name:'Rhytmic Activities', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_PEO03', code:'PEO03', name:'Individual / Dual Games Sports', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_PEO04', code:'PEO04', name:'Team Sports / Games', dept:'ee', units:2, sem:'catalog', active:true },
  { id:'s_ee_RES01a', code:'RES01a', name:'Research Methods', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ee_RES02', code:'RES02', name:'Research Project / Capstone Design', dept:'ee', units:1, sem:'catalog', active:true },
  { id:'s_ie_AEC02', code:'AEC02', name:'Principles of Economics', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_AEC04', code:'AEC04', name:'Financial Accounting', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_AEC05', code:'AEC05', name:'Managerial Accounting', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_BES01', code:'BES01', name:'Engineering Economics', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_BES04', code:'BES04', name:'Technopreneurship 101', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_BES05', code:'BES05', name:'Basic Occupational Safety and Health', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_CAD01', code:'CAD01', name:'Computer Aided Drafting', dept:'ie', units:1, sem:'catalog', active:true },
  { id:'s_ie_CHM01a', code:'CHM01a', name:'Chemistry for Engineers', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_CHM01aL', code:'CHM01aL', name:'Chemistry for Engineers (Lab)', dept:'ie', units:1, sem:'catalog', active:true },
  { id:'s_ie_EEN01a', code:'EEN01a', name:'Fundamentals of Electrical Circuits', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_GEC01', code:'GEC01', name:'The Life and the Works of Rizal', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_GEC02', code:'GEC02', name:'Understanding the Self', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_GEC03', code:'GEC03', name:'Redings in the Philippine History', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_GEC05', code:'GEC05', name:'Mathermatics in the Modern World', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_GEC07', code:'GEC07', name:'Art Appreciation', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_GEC08', code:'GEC08', name:'Science,Technology and Society', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_GEC09', code:'GEC09', name:'Ethics', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_GEC10', code:'GEC10', name:'Kontekswalisadong Komunikasyon sa Filipino', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s1', code:'IE101', name:'Engineering Management', dept:'ie', units:3, sem:'1st', active:true },
  { id:'s2', code:'IE102', name:'Operations Research', dept:'ie', units:3, sem:'1st', active:true },
  { id:'s_ie_IEE01', code:'IEE01', name:'Industrial Engineering Elective 1', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEE2', code:'IEE2', name:'IE Elective 2', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEE03', code:'IEE03', name:'IE Elective 3', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEN01', code:'IEN01', name:'Statistical Analysis for IE 1', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEN04', code:'IEN04', name:'Industrial Organization & Managment', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEN05', code:'IEN05', name:'Advanced Mathematics for IE', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEN06', code:'IEN06', name:'Work Study and Measurement Lec', dept:'ie', units:2, sem:'catalog', active:true },
  { id:'s_ie_IEN06L', code:'IEN06L', name:'Work Study and Measurement Lab', dept:'ie', units:1, sem:'catalog', active:true },
  { id:'s_ie_IEN07', code:'IEN07', name:'Operations Rerearch 1', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEN08', code:'IEN08', name:'Quality Management System', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEN09', code:'IEN09', name:'Ergonomics 1 Lec', dept:'ie', units:2, sem:'catalog', active:true },
  { id:'s_ie_IEN09L', code:'IEN09L', name:'Ergonomics 1 Lab', dept:'ie', units:1, sem:'catalog', active:true },
  { id:'s_ie_IEN10', code:'IEN10', name:'Operations Research 2', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEN11', code:'IEN11', name:'Operations Management Lec', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEN12', code:'IEN12', name:'Ergonomics 2 Lec', dept:'ie', units:2, sem:'catalog', active:true },
  { id:'s_ie_IEN12L', code:'IEN12L', name:'Ergonomics 2 Lab', dept:'ie', units:1, sem:'catalog', active:true },
  { id:'s_ie_IEN13', code:'IEN13', name:'Industry Computer Application', dept:'ie', units:1, sem:'catalog', active:true },
  { id:'s_ie_IEN13L', code:'IEN13L', name:'Industry Computer Application Lab', dept:'ie', units:2, sem:'catalog', active:true },
  { id:'s_ie_IEN14', code:'IEN14', name:'Project Feasibility', dept:'ie', units:2, sem:'catalog', active:true },
  { id:'s_ie_IEN14L', code:'IEN14L', name:'Project Feasibility Lab', dept:'ie', units:1, sem:'catalog', active:true },
  { id:'s_ie_IEN15', code:'IEN15', name:'Supply Chain Management', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEN16', code:'IEN16', name:'Information Systems', dept:'ie', units:2, sem:'catalog', active:true },
  { id:'s_ie_IEN16L', code:'IEN16L', name:'Information Systems Lab', dept:'ie', units:1, sem:'catalog', active:true },
  { id:'s_ie_IEN17', code:'IEN17', name:'Systems Engineering', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_IEN18', code:'IEN18', name:'IE Capstone Project Lec', dept:'ie', units:1, sem:'catalog', active:true },
  { id:'s_ie_IEN18L', code:'IEN18L', name:'IE Capstone Project Lab', dept:'ie', units:2, sem:'catalog', active:true },
  { id:'s_ie_IEN19', code:'IEN19', name:'IE Industry Immersion (240 Hours)', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_INE03L', code:'INE03L', name:'Industrial Materials and Processes Lab', dept:'ie', units:1, sem:'catalog', active:true },
  { id:'s_ie_MAT04', code:'MAT04', name:'Calculus 1 (Differential Calculus)', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_MAT07', code:'MAT07', name:'Differential Equations', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_MEC00', code:'MEC00', name:'Engineering Mechanics', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_MECE01', code:'MECE01', name:'Basic Thermodynamics', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_NSC01', code:'NSC01', name:'Environmental Science', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_ie_PEO01', code:'PEO01', name:'Physical Fitness', dept:'ie', units:2, sem:'catalog', active:true },
  { id:'s_ie_PEO03', code:'PEO03', name:'Individual/ Dual Sports', dept:'ie', units:2, sem:'catalog', active:true },
  { id:'s_ie_PEO04', code:'PEO04', name:'Team Sports and Games', dept:'ie', units:2, sem:'catalog', active:true },
  { id:'s_ie_PHY03', code:'PHY03', name:'Physics for Engineers (Calculus Based)', dept:'ie', units:3, sem:'catalog', active:true },
  { id:'s_me_BES01a', code:'BES01a', name:'Engineering Economics', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_BES02a', code:'BES02a', name:'Engineering Management', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_BES04', code:'BES04', name:'Technopreneurship 101', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_CHM01a', code:'CHM01a', name:'Chemistry for Engineers', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_CHM01aL', code:'CHM01aL', name:'Chemistry for Engineers Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_COE01', code:'COE01', name:'Mechanical Engineering Orientation', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_COM01', code:'COM01', name:'Computer Fundamental and Programming', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_COM02', code:'COM02', name:'Computer Application for ME', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_DRW01', code:'DRW01', name:'Engineering Drawing', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_ECE00', code:'ECE00', name:'Basic Electronics', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_ECE00L', code:'ECE00L', name:'Basic Electronics Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_EEN01A', code:'EEN01A', name:'Basic Electrical Engineering', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_EEN01AL', code:'EEN01AL', name:'Basic Electrical Engineering Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_GEC02', code:'GEC02', name:'Understanding the Self', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_GEC03', code:'GEC03', name:'Mathematics in the Modern World', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_GEC05', code:'GEC05', name:'Mathematics in the Modern World', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_GEC07', code:'GEC07', name:'Art Appreciation', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_GEC09', code:'GEC09', name:'Ethics', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_GEC10', code:'GEC10', name:'Kontekswalisadong Komunuikasyon sa Filipino', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_GEC11', code:'GEC11', name:'Filipino sa Iba\'t Ibang Disiplina', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_GEC13', code:'GEC13', name:'Literature of the Philippines', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MAT04', code:'MAT04', name:'Calculus 1 (Differential)', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MAT08', code:'MAT08', name:'Engineering Data and Analysis', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MAT10f', code:'MAT10f', name:'Advance Mathematics for ME', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MCE01', code:'MCE01', name:'Thermodynamics 1', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MCE02', code:'MCE02', name:'Thermodynamics 2', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MCE03', code:'MCE03', name:'Workshop, Theory and Practice', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE04', code:'MCE04', name:'Machine Shop Theory', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MCE05', code:'MCE05', name:'Machine Elements', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MCE05L', code:'MCE05L', name:'Machine Elements Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE06', code:'MCE06', name:'Heat Transfer', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MCE07', code:'MCE07', name:'Vibration Engineering', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MCE08', code:'MCE08', name:'Refrigeration System', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MCE09', code:'MCE09', name:'Fluid Machinery', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MCE10', code:'MCE10', name:'Combustion Engineering', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MCE11', code:'MCE11', name:'ME Laboratory 1', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE12', code:'MCE12', name:'Material Science and Engineering for ME', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MCE12L', code:'MCE12L', name:'Material Science and Engineering for ME Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE13', code:'MCE13', name:'DC and AC Machineris', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MCE13L', code:'MCE13L', name:'DC and AC Machineris Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE14', code:'MCE14', name:'ME Elective 1 Electro Pneumatics', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE14L', code:'MCE14L', name:'ME Elective 1 Electro Pneumatics Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE15', code:'MCE15', name:'Machine Design', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MCE17', code:'MCE17', name:'Control Engineering', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MCE17L', code:'MCE17L', name:'Control Engineering Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE18', code:'MCE18', name:'Air Conditioning and Ventilation System', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MCE19', code:'MCE19', name:'Power Plant Design with Renewable Energy', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MCE19L', code:'MCE19L', name:'Power Plant Design with Renewable Energy Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE20', code:'MCE20', name:'ME Elective 2 Mechatronics', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE20L', code:'MCE20L', name:'ME Elective 2 Mechatronics Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE21', code:'MCE21', name:'ME Laboratory 3', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MCE22', code:'MCE22', name:'Machine Design 2', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MCE22L', code:'MCE22L', name:'Machine Design 2', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE23', code:'MCE23', name:'Industrial Plant Engineering', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MCE23L', code:'MCE23L', name:'Industrial Plant Engineering Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_MCE25', code:'MCE25', name:'Basic Occupational Safety and Health', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MCE26', code:'MCE26', name:'Integrative Course for ME', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s6', code:'ME101', name:'Thermodynamics', dept:'me', units:3, sem:'1st', active:true },
  { id:'s_me_MEC02', code:'MEC02', name:'Dynamics of Rigid Bodies', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_MEC03', code:'MEC03', name:'Mechanics of Deformable Bodies', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_MEC04c', code:'MEC04c', name:'Fluid Mechanics', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_OJT', code:'OJT', name:'On the Job Training / Summer', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_PATHFIT03', code:'PATHFIT03', name:'Rhythmic Activities and Sports', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_PATHFIT04', code:'PATHFIT04', name:'Recreational Activities', dept:'me', units:2, sem:'catalog', active:true },
  { id:'s_me_PHY03', code:'PHY03', name:'Physics for Engineers', dept:'me', units:3, sem:'catalog', active:true },
  { id:'s_me_PHY03L', code:'PHY03L', name:'Physics for Engineers Lab', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_RES01', code:'RES01', name:'Methods of Research for ME', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_RES02a', code:'RES02a', name:'ME Project Study 1', dept:'me', units:1, sem:'catalog', active:true },
  { id:'s_me_RES02b', code:'RES02b', name:'Project Study 2', dept:'me', units:1, sem:'catalog', active:true },
];


// PDF has no weekly matrix — sample placements using PDF section names & rooms
const SCHEDULES = [
  { id:'sch1', subjectId:'s_ee_CHM01', professorId:'p_ee_1', roomId:'ee_mdhp209', dept:'ee', section:'BSEE IGI', days:['Monday','Wednesday'], timeStart:'07:30', timeEnd:'09:00', color:'blue', setLabel:null, labLabel:null, schYear:'1st Year', schSem:'1st Semester' },
  { id:'sch2', subjectId:'s_cpe_MAT04', professorId:'p_cpe_3', roomId:'cpe_302', dept:'cpe', section:'BSCPE IGE', days:['Tuesday','Thursday'], timeStart:'09:00', timeEnd:'10:30', color:'blue', setLabel:null, labLabel:null, schYear:'1st Year', schSem:'1st Semester' },
  { id:'sch3', subjectId:'s_cpe_GEC05', professorId:'p_cpe_2', roomId:'cpe_101', dept:'cpe', section:'BSCPE IGE', days:['Monday','Wednesday'], timeStart:'10:30', timeEnd:'12:00', color:'blue', setLabel:null, labLabel:null, schYear:'1st Year', schSem:'1st Semester' },
  { id:'sch4', subjectId:'s_ie_MAT04', professorId:'p_ie_2', roomId:'ie_mdhp303', dept:'ie', section:'BSIE IGK', days:['Monday','Wednesday','Friday'], timeStart:'07:30', timeEnd:'08:30', color:'green', setLabel:null, labLabel:null, schYear:'1st Year', schSem:'1st Semester' },
  { id:'sch5', subjectId:'s_ce_CVE01', professorId:'p_ce_3', roomId:'ce_mdhp103', dept:'ce', section:'BSCE IGA', days:['Tuesday','Thursday'], timeStart:'07:30', timeEnd:'09:00', color:'blue', setLabel:null, labLabel:null, schYear:'1st Year', schSem:'1st Semester' },
  { id:'sch6', subjectId:'s_me_COE01', professorId:'p_me_2', roomId:'me_mhdp102', dept:'me', section:'BSME IGM', days:['Monday','Wednesday'], timeStart:'13:00', timeEnd:'14:30', color:'blue', setLabel:null, labLabel:null, schYear:'1st Year', schSem:'1st Semester' },
  { id:'sch7', subjectId:'s_ece_MAT04', professorId:'p_ece_1', roomId:'ece_mhdp201', dept:'ece', section:'BSECE IGG', days:['Tuesday','Thursday'], timeStart:'14:30', timeEnd:'16:00', color:'blue', setLabel:null, labLabel:null, schYear:'1st Year', schSem:'1st Semester' },
  { id:'sch8', subjectId:'s_ie_CHM01aL', professorId:'p_ie_1', roomId:'lab_ie_a', dept:'ie', section:'BSIE IGK', days:['Friday'], timeStart:'09:00', timeEnd:'12:00', color:'purple', setLabel:null, labLabel:null, schYear:'1st Year', schSem:'1st Semester' },
];

/** Sample borrow requests: scoped by dept so each chairperson sees Incoming (toDept) / Outgoing (fromDept) on the Requests page. */
const REQUESTS = [
  { id:'req1', fromDept:'cpe', toDept:'ee', roomId:'ee_lab_b', subjectId:'s9', section:'BSCPE IGF', professorId:'p_cpe_2', days:['Wednesday'], timeStart:'15:00', timeEnd:'17:00', reason:'Lab fully booked', status:'pending', created:'2026-01-15' },
  { id:'req2', fromDept:'ee', toDept:'ie', roomId:'ie_mdhp305', subjectId:'s3', section:'BSEE IGI', professorId:'p_ee_2', days:['Monday'], timeStart:'10:30', timeEnd:'12:00', reason:'Exam block — need larger room', status:'pending', created:'2026-01-12' },
  { id:'req3', fromDept:'me', toDept:'ce', roomId:'ce_mdhp107', subjectId:'s6', section:'BSME IGM', professorId:'p_me_2', days:['Tuesday','Thursday'], timeStart:'13:00', timeEnd:'14:30', reason:'Dept workshop', status:'pending', created:'2026-01-10' },
  { id:'req4', fromDept:'cpe', toDept:'ece', roomId:'ece_mhdp203', subjectId:'s8', section:'BSCPE IGE', professorId:'p_cpe_3', days:['Friday'], timeStart:'09:00', timeEnd:'10:30', reason:'', status:'approved', created:'2026-01-08' },
  { id:'req5', fromDept:'ie', toDept:'me', roomId:'me_mdhp108', subjectId:'s1', section:'BSIE IGK', professorId:'p_ie_2', days:['Wednesday'], timeStart:'07:30', timeEnd:'09:00', reason:'Joint lecture', status:'pending', created:'2026-01-14' },
  { id:'req6', fromDept:'ce', toDept:'ece', roomId:'ece_mhdp205', subjectId:'s5', section:'BSCE IGA', professorId:'p_ce_3', days:['Monday'], timeStart:'14:30', timeEnd:'16:00', reason:'', status:'pending', created:'2026-01-11' },
  { id:'req7', fromDept:'cpe', toDept:'ee', roomId:'ee_mdhp211', subjectId:'s_cpe_MAT04', section:'BSCPE IGE', professorId:'p_cpe_3', days:['Thursday'], timeStart:'16:00', timeEnd:'17:30', reason:'Make-up class', status:'pending', created:'2026-01-16' },
  { id:'req8', fromDept:'ece', toDept:'ie', roomId:'lab_ie_a', subjectId:'s7', section:'BSECE IGG', professorId:'p_ece_2', days:['Tuesday'], timeStart:'13:30', timeEnd:'16:00', reason:'Lab equipment', status:'declined', created:'2026-01-05' },
  { id:'req9', fromDept:'ee', toDept:'cpe', roomId:'lab_cpe_b', subjectId:'s4', section:'BSEE IGI', professorId:'p_ee_3', days:['Monday','Wednesday'], timeStart:'15:00', timeEnd:'16:30', reason:'Circuits lab overflow', status:'pending', created:'2026-01-17' },
  /** Prototype incoming (IE chair demo login: ie.chair@plm.edu.ph) — ensures a visible Requests notification. */
  { id:'req_proto_demo', fromDept:'me', toDept:'ie', roomId:'ie_mdhp307', subjectId:'s6', section:'BSME IGM', professorId:'p_me_3', days:['Friday'], timeStart:'10:30', timeEnd:'12:00', reason:'[Demo prototype] Borrow IE classroom for cross-dept activity', status:'pending', created:'2026-04-18' },
];

const DAYS = ['Monday','Tuesday','Wednesday','Thursday','Friday'];
const timeSlots = ['07:30','08:00','08:30','09:00','09:30','10:00','10:30','11:00','11:30','12:00','12:30','13:00','13:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00','17:30','18:00','18:30','19:00','19:30'];

// Sample section labels for schedule / request dropdowns (merged with sections already on timetables)
const SECTION_SAMPLES_BY_DEPT = {
  ie: ['BSIE IGK', 'BSIE IGL', 'BSIE IIGK', 'BSIE IIGL', 'BSIE IIIGK', 'BSIE IIIGL', 'BSIE IVGK', 'BSIE IVGL'],
  cpe: ['BSCPE IGE', 'BSCPE IGF', 'BSCPE IIGE', 'BSCPE IIGF', 'BSCPE IIIGE', 'BSCPE IIIGF', 'BSCPE IVGE', 'BSCPE IVGF'],
  ce: ['BSCE IGA', 'BSCE IGB', 'BSCE IIGA', 'BSCE IIGB', 'BSCE IIIGA', 'BSCE IIIGB', 'BSCE IVGA', 'BSCE IVGB'],
  ee: ['BSEE IGI', 'BSEE IGJ', 'BSEE IIGI', 'BSEE IIGJ', 'BSEE IIIGI', 'BSEE IIIGJ', 'BSEE IVGI', 'BSEE IVGJ'],
  me: ['BSME IGM', 'BSME IGN', 'BSME IIGM', 'BSME IIGN', 'BSME IIIGM', 'BSME IIIGN', 'BSME IVGM', 'BSME IVGN'],
  ece: ['BSECE IGG', 'BSECE IGH', 'BSECE IIGG', 'BSECE IIGH', 'BSECE IIIGG', 'BSECE IIIGH', 'BSECE IVGG', 'BSECE IVGH'],
};

// Admin curriculum catalog (separate from subject master list used for scheduling links)
// IE: CEN SCHEDULING IE_INFORMATION.pdf — lecUnits, labUnits, units (total).
// CPE: CEN SCHEDULING CPE_INFORMATION.pdf — same.
const CURRICULUM_DATA = [
  { id:'cc_me_1', dept:'me', year:'1st Year', semester:'1st Semester', courseCode:'ME 100', courseName:'Mechanical Engineering Orientation Block', subjectCode:'COE01', subjectName:'Mechanical Engineering Orientation', lecUnits:2, labUnits:0, units:2, section:'BSME IGM' },{ id:'cc_ie_001', dept:'ie', year:'1st Year', semester:'1st Semester', courseCode:'CHM01a', subjectName:"Chemistry for Engineers", lecUnits:3, labUnits:0, units:3, courseName:"Chemistry for Engineers", subjectCode:'CHM01a', section:'' },
  { id:'cc_ie_002', dept:'ie', year:'1st Year', semester:'1st Semester', courseCode:'CHM01aL', subjectName:"Chemistry for Engineers (Lab)", lecUnits:0, labUnits:1, units:1, courseName:"Chemistry for Engineers (Lab)", subjectCode:'CHM01aL', section:'' },
  { id:'cc_ie_003', dept:'ie', year:'1st Year', semester:'1st Semester', courseCode:'GEC02', subjectName:"Understanding the Self", lecUnits:3, labUnits:0, units:3, courseName:"Understanding the Self", subjectCode:'GEC02', section:'' },
  { id:'cc_ie_004', dept:'ie', year:'1st Year', semester:'1st Semester', courseCode:'GEC03', subjectName:"Readings in the Philippine History", lecUnits:3, labUnits:0, units:3, courseName:"Readings in the Philippine History", subjectCode:'GEC03', section:'' },
  { id:'cc_ie_005', dept:'ie', year:'1st Year', semester:'1st Semester', courseCode:'GEC05', subjectName:"Mathematics in the Modern World", lecUnits:3, labUnits:0, units:3, courseName:"Mathematics in the Modern World", subjectCode:'GEC05', section:'' },
  { id:'cc_ie_006', dept:'ie', year:'1st Year', semester:'1st Semester', courseCode:'GEC10', subjectName:"Kontekswalisadong Komunikasyon sa Filipino", lecUnits:3, labUnits:0, units:3, courseName:"Kontekswalisadong Komunikasyon sa Filipino", subjectCode:'GEC10', section:'' },
  { id:'cc_ie_007', dept:'ie', year:'1st Year', semester:'1st Semester', courseCode:'MAT04', subjectName:"Calculus 1 (Differential Calculus)", lecUnits:3, labUnits:0, units:3, courseName:"Calculus 1 (Differential Calculus)", subjectCode:'MAT04', section:'' },
  { id:'cc_ie_008', dept:'ie', year:'1st Year', semester:'1st Semester', courseCode:'PEO01', subjectName:"Physical Fitness", lecUnits:2, labUnits:0, units:2, courseName:"Physical Fitness", subjectCode:'PEO01', section:'' },
  { id:'cc_ie_009', dept:'ie', year:'1st Year', semester:'1st Semester', courseCode:'NST01', subjectName:"ROTC", lecUnits:0, labUnits:3, units:3, courseName:"ROTC", subjectCode:'NST01', section:'' },
  { id:'cc_ie_010', dept:'ie', year:'1st Year', semester:'2nd Semester', courseCode:'GEC04', subjectName:"The Contemporary World", lecUnits:3, labUnits:0, units:3, courseName:"The Contemporary World", subjectCode:'GEC04', section:'' },
  { id:'cc_ie_011', dept:'ie', year:'1st Year', semester:'2nd Semester', courseCode:'GEC06', subjectName:"Purposive Communication", lecUnits:3, labUnits:0, units:3, courseName:"Purposive Communication", subjectCode:'GEC06', section:'' },
  { id:'cc_ie_012', dept:'ie', year:'1st Year', semester:'2nd Semester', courseCode:'GEC11', subjectName:"Filipino sa Iba't ibang Disiplina", lecUnits:3, labUnits:0, units:3, courseName:"Filipino sa Iba't ibang Disiplina", subjectCode:'GEC11', section:'' },
  { id:'cc_ie_013', dept:'ie', year:'1st Year', semester:'2nd Semester', courseCode:'IEN01', subjectName:"Statistical Analysis for IE 1", lecUnits:3, labUnits:0, units:3, courseName:"Statistical Analysis for IE 1", subjectCode:'IEN01', section:'' },
  { id:'cc_ie_014', dept:'ie', year:'1st Year', semester:'2nd Semester', courseCode:'PHY03', subjectName:"Physics for Engineers (Calculus Based)", lecUnits:3, labUnits:0, units:3, courseName:"Physics for Engineers (Calculus Based)", subjectCode:'PHY03', section:'' },
  { id:'cc_ie_015', dept:'ie', year:'1st Year', semester:'2nd Semester', courseCode:'PHY03L', subjectName:"Physics for Engineers (Calculus Based) Lab", lecUnits:0, labUnits:1, units:1, courseName:"Physics for Engineers (Calculus Based) Lab", subjectCode:'PHY03L', section:'' },
  { id:'cc_ie_016', dept:'ie', year:'1st Year', semester:'2nd Semester', courseCode:'PEO02', subjectName:"Rhythmic Activities", lecUnits:2, labUnits:0, units:2, courseName:"Rhythmic Activities", subjectCode:'PEO02', section:'' },
  { id:'cc_ie_017', dept:'ie', year:'1st Year', semester:'2nd Semester', courseCode:'NST02', subjectName:"ROTC2", lecUnits:0, labUnits:3, units:3, courseName:"ROTC2", subjectCode:'NST02', section:'' },
  { id:'cc_ie_018', dept:'ie', year:'2nd Year', semester:'1st Semester', courseCode:'COM01', subjectName:"Computer Fundamentals and Programming (Lab)", lecUnits:0, labUnits:1, units:1, courseName:"Computer Fundamentals and Programming (Lab)", subjectCode:'COM01', section:'' },
  { id:'cc_ie_019', dept:'ie', year:'2nd Year', semester:'1st Semester', courseCode:'GEC13', subjectName:"Literature of the Philippines", lecUnits:3, labUnits:0, units:3, courseName:"Literature of the Philippines", subjectCode:'GEC13', section:'' },
  { id:'cc_ie_020', dept:'ie', year:'2nd Year', semester:'1st Semester', courseCode:'IEN02', subjectName:"Statistical Analysis for IE 2", lecUnits:3, labUnits:0, units:3, courseName:"Statistical Analysis for IE 2", subjectCode:'IEN02', section:'' },
  { id:'cc_ie_021', dept:'ie', year:'2nd Year', semester:'1st Semester', courseCode:'IEN03', subjectName:"Industrial Materials and Processes Lec", lecUnits:2, labUnits:0, units:2, courseName:"Industrial Materials and Processes Lec", subjectCode:'IEN03', section:'' },
  { id:'cc_ie_022', dept:'ie', year:'2nd Year', semester:'1st Semester', courseCode:'IEN03L', subjectName:"Industrial Materials and Processes Lab", lecUnits:0, labUnits:1, units:1, courseName:"Industrial Materials and Processes Lab", subjectCode:'IEN03L', section:'' },
  { id:'cc_ie_023', dept:'ie', year:'2nd Year', semester:'1st Semester', courseCode:'IEN04', subjectName:"Industrial Organization & Management", lecUnits:3, labUnits:0, units:3, courseName:"Industrial Organization & Management", subjectCode:'IEN04', section:'' },
  { id:'cc_ie_024', dept:'ie', year:'2nd Year', semester:'1st Semester', courseCode:'MAT07', subjectName:"Differential Equations", lecUnits:3, labUnits:0, units:3, courseName:"Differential Equations", subjectCode:'MAT07', section:'' },
  { id:'cc_ie_025', dept:'ie', year:'2nd Year', semester:'1st Semester', courseCode:'MEC00', subjectName:"Engineering Mechanics", lecUnits:3, labUnits:0, units:3, courseName:"Engineering Mechanics", subjectCode:'MEC00', section:'' },
  { id:'cc_ie_026', dept:'ie', year:'2nd Year', semester:'1st Semester', courseCode:'PEO03', subjectName:"Individual/Dual Sports", lecUnits:2, labUnits:0, units:2, courseName:"Individual/Dual Sports", subjectCode:'PEO03', section:'' },
  { id:'cc_ie_027', dept:'ie', year:'2nd Year', semester:'2nd Semester', courseCode:'AEC02', subjectName:"Principles of Economics", lecUnits:3, labUnits:0, units:3, courseName:"Principles of Economics", subjectCode:'AEC02', section:'' },
  { id:'cc_ie_028', dept:'ie', year:'2nd Year', semester:'2nd Semester', courseCode:'BES01', subjectName:"Engineering Economics", lecUnits:3, labUnits:0, units:3, courseName:"Engineering Economics", subjectCode:'BES01', section:'' },
  { id:'cc_ie_029', dept:'ie', year:'2nd Year', semester:'2nd Semester', courseCode:'BES05', subjectName:"Basic Occupational Safety and Health", lecUnits:3, labUnits:0, units:3, courseName:"Basic Occupational Safety and Health", subjectCode:'BES05', section:'' },
  { id:'cc_ie_030', dept:'ie', year:'2nd Year', semester:'2nd Semester', courseCode:'CAD01', subjectName:"Computer Aided Drafting", lecUnits:0, labUnits:1, units:1, courseName:"Computer Aided Drafting", subjectCode:'CAD01', section:'' },
  { id:'cc_ie_031', dept:'ie', year:'2nd Year', semester:'2nd Semester', courseCode:'IEN05', subjectName:"Advanced Mathematics for IE", lecUnits:3, labUnits:0, units:3, courseName:"Advanced Mathematics for IE", subjectCode:'IEN05', section:'' },
  { id:'cc_ie_032', dept:'ie', year:'2nd Year', semester:'2nd Semester', courseCode:'IEN06', subjectName:"Work Study and Measurement Lec", lecUnits:2, labUnits:0, units:2, courseName:"Work Study and Measurement Lec", subjectCode:'IEN06', section:'' },
  { id:'cc_ie_033', dept:'ie', year:'2nd Year', semester:'2nd Semester', courseCode:'IEN06L', subjectName:"Work Study and Measurement Lab", lecUnits:0, labUnits:1, units:1, courseName:"Work Study and Measurement Lab", subjectCode:'IEN06L', section:'' },
  { id:'cc_ie_034', dept:'ie', year:'2nd Year', semester:'2nd Semester', courseCode:'MECE01', subjectName:"Basic Thermodynamics", lecUnits:3, labUnits:0, units:3, courseName:"Basic Thermodynamics", subjectCode:'MECE01', section:'' },
  { id:'cc_ie_035', dept:'ie', year:'2nd Year', semester:'2nd Semester', courseCode:'PEO04', subjectName:"Team Sports and Games", lecUnits:2, labUnits:0, units:2, courseName:"Team Sports and Games", subjectCode:'PEO04', section:'' },
  { id:'cc_ie_036', dept:'ie', year:'3rd Year', semester:'1st Semester', courseCode:'AEC04', subjectName:"Financial Accounting", lecUnits:3, labUnits:0, units:3, courseName:"Financial Accounting", subjectCode:'AEC04', section:'' },
  { id:'cc_ie_037', dept:'ie', year:'3rd Year', semester:'1st Semester', courseCode:'EEN01a', subjectName:"Fundamentals of Electrical Circuits", lecUnits:3, labUnits:0, units:3, courseName:"Fundamentals of Electrical Circuits", subjectCode:'EEN01a', section:'' },
  { id:'cc_ie_038', dept:'ie', year:'3rd Year', semester:'1st Semester', courseCode:'GEC09', subjectName:"Ethics", lecUnits:3, labUnits:0, units:3, courseName:"Ethics", subjectCode:'GEC09', section:'' },
  { id:'cc_ie_039', dept:'ie', year:'3rd Year', semester:'1st Semester', courseCode:'IEE01', subjectName:"Industrial Engineering Elective 1", lecUnits:3, labUnits:0, units:3, courseName:"Industrial Engineering Elective 1", subjectCode:'IEE01', section:'' },
  { id:'cc_ie_040', dept:'ie', year:'3rd Year', semester:'1st Semester', courseCode:'IEN07', subjectName:"Operations Research 1", lecUnits:3, labUnits:0, units:3, courseName:"Operations Research 1", subjectCode:'IEN07', section:'' },
  { id:'cc_ie_041', dept:'ie', year:'3rd Year', semester:'1st Semester', courseCode:'IEN08', subjectName:"Quality Management System", lecUnits:3, labUnits:0, units:3, courseName:"Quality Management System", subjectCode:'IEN08', section:'' },
  { id:'cc_ie_042', dept:'ie', year:'3rd Year', semester:'1st Semester', courseCode:'IEN09', subjectName:"Ergonomics 1 Lec", lecUnits:2, labUnits:0, units:2, courseName:"Ergonomics 1 Lec", subjectCode:'IEN09', section:'' },
  { id:'cc_ie_043', dept:'ie', year:'3rd Year', semester:'1st Semester', courseCode:'IEN09L', subjectName:"Ergonomics 1 Lab", lecUnits:0, labUnits:1, units:1, courseName:"Ergonomics 1 Lab", subjectCode:'IEN09L', section:'' },
  { id:'cc_ie_044', dept:'ie', year:'3rd Year', semester:'1st Semester', courseCode:'NSC01', subjectName:"Environmental Science", lecUnits:3, labUnits:0, units:3, courseName:"Environmental Science", subjectCode:'NSC01', section:'' },
  { id:'cc_ie_045', dept:'ie', year:'3rd Year', semester:'2nd Semester', courseCode:'AEC05', subjectName:"Managerial Accounting", lecUnits:3, labUnits:0, units:3, courseName:"Managerial Accounting", subjectCode:'AEC05', section:'' },
  { id:'cc_ie_046', dept:'ie', year:'3rd Year', semester:'2nd Semester', courseCode:'BES04', subjectName:"Technopreneurship 101", lecUnits:3, labUnits:0, units:3, courseName:"Technopreneurship 101", subjectCode:'BES04', section:'' },
  { id:'cc_ie_047', dept:'ie', year:'3rd Year', semester:'2nd Semester', courseCode:'GEC08', subjectName:"Science, Technology and Society", lecUnits:3, labUnits:0, units:3, courseName:"Science, Technology and Society", subjectCode:'GEC08', section:'' },
  { id:'cc_ie_048', dept:'ie', year:'3rd Year', semester:'2nd Semester', courseCode:'IEE02', subjectName:"IE Elective 2", lecUnits:3, labUnits:0, units:3, courseName:"IE Elective 2", subjectCode:'IEE02', section:'' },
  { id:'cc_ie_049', dept:'ie', year:'3rd Year', semester:'2nd Semester', courseCode:'IEN13', subjectName:"Industry Computer Application", lecUnits:1, labUnits:0, units:1, courseName:"Industry Computer Application", subjectCode:'IEN13', section:'' },
  { id:'cc_ie_050', dept:'ie', year:'3rd Year', semester:'2nd Semester', courseCode:'IEN13L', subjectName:"Industry Computer Application Lab", lecUnits:0, labUnits:2, units:2, courseName:"Industry Computer Application Lab", subjectCode:'IEN13L', section:'' },
  { id:'cc_ie_051', dept:'ie', year:'3rd Year', semester:'2nd Semester', courseCode:'IEN10', subjectName:"Operations Research 2", lecUnits:3, labUnits:0, units:3, courseName:"Operations Research 2", subjectCode:'IEN10', section:'' },
  { id:'cc_ie_052', dept:'ie', year:'3rd Year', semester:'2nd Semester', courseCode:'IEN11', subjectName:"Operations Management Lec", lecUnits:3, labUnits:0, units:3, courseName:"Operations Management Lec", subjectCode:'IEN11', section:'' },
  { id:'cc_ie_053', dept:'ie', year:'3rd Year', semester:'2nd Semester', courseCode:'IEN12', subjectName:"Ergonomics 2 Lec", lecUnits:2, labUnits:0, units:2, courseName:"Ergonomics 2 Lec", subjectCode:'IEN12', section:'' },
  { id:'cc_ie_054', dept:'ie', year:'3rd Year', semester:'2nd Semester', courseCode:'IEN12L', subjectName:"Ergonomics 2 Lab", lecUnits:0, labUnits:1, units:1, courseName:"Ergonomics 2 Lab", subjectCode:'IEN12L', section:'' },
  { id:'cc_ie_055', dept:'ie', year:'3rd Year', semester:'Midyear', courseCode:'IEN19', subjectName:"IE Industry Immersion (240 Hours)", lecUnits:3, labUnits:0, units:3, courseName:"IE Industry Immersion (240 Hours)", subjectCode:'IEN19', section:'' },
  { id:'cc_ie_056', dept:'ie', year:'4th Year', semester:'1st Semester', courseCode:'GEC01', subjectName:"The Life and the Works of Rizal", lecUnits:3, labUnits:0, units:3, courseName:"The Life and the Works of Rizal", subjectCode:'GEC01', section:'' },
  { id:'cc_ie_057', dept:'ie', year:'4th Year', semester:'1st Semester', courseCode:'GEC07', subjectName:"Art Appreciation", lecUnits:3, labUnits:0, units:3, courseName:"Art Appreciation", subjectCode:'GEC07', section:'' },
  { id:'cc_ie_058', dept:'ie', year:'4th Year', semester:'1st Semester', courseCode:'IEE03', subjectName:"IE Elective 3", lecUnits:3, labUnits:0, units:3, courseName:"IE Elective 3", subjectCode:'IEE03', section:'' },
  { id:'cc_ie_059', dept:'ie', year:'4th Year', semester:'1st Semester', courseCode:'IEN14', subjectName:"Project Feasibility", lecUnits:2, labUnits:0, units:2, courseName:"Project Feasibility", subjectCode:'IEN14', section:'' },
  { id:'cc_ie_060', dept:'ie', year:'4th Year', semester:'1st Semester', courseCode:'IEN14L', subjectName:"Project Feasibility Lab", lecUnits:0, labUnits:1, units:1, courseName:"Project Feasibility Lab", subjectCode:'IEN14L', section:'' },
  { id:'cc_ie_061', dept:'ie', year:'4th Year', semester:'1st Semester', courseCode:'IEN15', subjectName:"Supply Chain Management", lecUnits:3, labUnits:0, units:3, courseName:"Supply Chain Management", subjectCode:'IEN15', section:'' },
  { id:'cc_ie_062', dept:'ie', year:'4th Year', semester:'1st Semester', courseCode:'IEN16', subjectName:"Information Systems", lecUnits:2, labUnits:0, units:2, courseName:"Information Systems", subjectCode:'IEN16', section:'' },
  { id:'cc_ie_063', dept:'ie', year:'4th Year', semester:'1st Semester', courseCode:'IEN16L', subjectName:"Information Systems Lab", lecUnits:0, labUnits:1, units:1, courseName:"Information Systems Lab", subjectCode:'IEN16L', section:'' },
  { id:'cc_ie_064', dept:'ie', year:'4th Year', semester:'1st Semester', courseCode:'IEN17', subjectName:"Systems Engineering", lecUnits:3, labUnits:0, units:3, courseName:"Systems Engineering", subjectCode:'IEN17', section:'' },
  { id:'cc_ie_065', dept:'ie', year:'4th Year', semester:'2nd Semester', courseCode:'IEN18', subjectName:"IE Capstone Project Lec", lecUnits:1, labUnits:0, units:1, courseName:"IE Capstone Project Lec", subjectCode:'IEN18', section:'' },
  { id:'cc_ie_066', dept:'ie', year:'4th Year', semester:'2nd Semester', courseCode:'IEN18L', subjectName:"IE Capstone Project Lab", lecUnits:0, labUnits:2, units:2, courseName:"IE Capstone Project Lab", subjectCode:'IEN18L', section:'' },{ id:'cc_cpe_001', dept:'cpe', year:'1st Year', semester:'1st Semester', courseCode:'GEC04', subjectName:"The Contemporary World", lecUnits:3, labUnits:0, units:3, courseName:"The Contemporary World", subjectCode:'GEC04', section:'' },
  { id:'cc_cpe_002', dept:'cpe', year:'1st Year', semester:'1st Semester', courseCode:'GEC05', subjectName:"Mathematics in the Modern World", lecUnits:3, labUnits:0, units:3, courseName:"Mathematics in the Modern World", subjectCode:'GEC05', section:'' },
  { id:'cc_cpe_003', dept:'cpe', year:'1st Year', semester:'1st Semester', courseCode:'GEC08', subjectName:"Science, Technology and Society", lecUnits:3, labUnits:0, units:3, courseName:"Science, Technology and Society", subjectCode:'GEC08', section:'' },
  { id:'cc_cpe_004', dept:'cpe', year:'1st Year', semester:'1st Semester', courseCode:'GEC10', subjectName:"Kontekswalisadong Komunikasyon sa Filipino", lecUnits:3, labUnits:0, units:3, courseName:"Kontekswalisadong Komunikasyon sa Filipino", subjectCode:'GEC10', section:'' },
  { id:'cc_cpe_005', dept:'cpe', year:'1st Year', semester:'1st Semester', courseCode:'MAT04', subjectName:"Calculus 1 (Differential)", lecUnits:3, labUnits:0, units:3, courseName:"Calculus 1 (Differential)", subjectCode:'MAT04', section:'' },
  { id:'cc_cpe_006', dept:'cpe', year:'1st Year', semester:'1st Semester', courseCode:'CHM01a', subjectName:"Chemistry for Engineers", lecUnits:3, labUnits:0, units:3, courseName:"Chemistry for Engineers", subjectCode:'CHM01a', section:'' },
  { id:'cc_cpe_007', dept:'cpe', year:'1st Year', semester:'1st Semester', courseCode:'CHM01aL', subjectName:"Chemistry for Engineers (Lab)", lecUnits:0, labUnits:1, units:1, courseName:"Chemistry for Engineers (Lab)", subjectCode:'CHM01aL', section:'' },
  { id:'cc_cpe_008', dept:'cpe', year:'1st Year', semester:'1st Semester', courseCode:'COE01', subjectName:"Computer Engineering as a Discipline", lecUnits:1, labUnits:0, units:1, courseName:"Computer Engineering as a Discipline", subjectCode:'COE01', section:'' },
  { id:'cc_cpe_009', dept:'cpe', year:'1st Year', semester:'1st Semester', courseCode:'PEO01', subjectName:"Physical Fitness", lecUnits:2, labUnits:0, units:2, courseName:"Physical Fitness", subjectCode:'PEO01', section:'' },
  { id:'cc_cpe_010', dept:'cpe', year:'1st Year', semester:'1st Semester', courseCode:'NST01', subjectName:"National Service Training Program 1", lecUnits:3, labUnits:0, units:3, courseName:"National Service Training Program 1", subjectCode:'NST01', section:'' },
  { id:'cc_cpe_011', dept:'cpe', year:'1st Year', semester:'2nd Semester', courseCode:'GEC02', subjectName:"Understanding the Self", lecUnits:3, labUnits:0, units:3, courseName:"Understanding the Self", subjectCode:'GEC02', section:'' },
  { id:'cc_cpe_012', dept:'cpe', year:'1st Year', semester:'2nd Semester', courseCode:'GEC03', subjectName:"Readings in Philippine History", lecUnits:3, labUnits:0, units:3, courseName:"Readings in Philippine History", subjectCode:'GEC03', section:'' },
  { id:'cc_cpe_013', dept:'cpe', year:'1st Year', semester:'2nd Semester', courseCode:'GEC06', subjectName:"Purposive Communication", lecUnits:3, labUnits:0, units:3, courseName:"Purposive Communication", subjectCode:'GEC06', section:'' },
  { id:'cc_cpe_014', dept:'cpe', year:'1st Year', semester:'2nd Semester', courseCode:'GEC11', subjectName:"Filipino sa Iba't Ibang Disiplina", lecUnits:3, labUnits:0, units:3, courseName:"Filipino sa Iba't Ibang Disiplina", subjectCode:'GEC11', section:'' },
  { id:'cc_cpe_015', dept:'cpe', year:'1st Year', semester:'2nd Semester', courseCode:'MAT05', subjectName:"Calculus 2 (Integral)", lecUnits:3, labUnits:0, units:3, courseName:"Calculus 2 (Integral)", subjectCode:'MAT05', section:'' },
  { id:'cc_cpe_016', dept:'cpe', year:'1st Year', semester:'2nd Semester', courseCode:'PHY03', subjectName:"Physics for Engineers", lecUnits:3, labUnits:0, units:3, courseName:"Physics for Engineers", subjectCode:'PHY03', section:'' },
  { id:'cc_cpe_017', dept:'cpe', year:'1st Year', semester:'2nd Semester', courseCode:'PHY03L', subjectName:"Physics for Engineers (Lab)", lecUnits:0, labUnits:1, units:1, courseName:"Physics for Engineers (Lab)", subjectCode:'PHY03L', section:'' },
  { id:'cc_cpe_018', dept:'cpe', year:'1st Year', semester:'2nd Semester', courseCode:'PEO02', subjectName:"Rhythmic Activities", lecUnits:2, labUnits:0, units:2, courseName:"Rhythmic Activities", subjectCode:'PEO02', section:'' },
  { id:'cc_cpe_019', dept:'cpe', year:'1st Year', semester:'2nd Semester', courseCode:'NST02', subjectName:"National Service Training Program", lecUnits:3, labUnits:0, units:3, courseName:"National Service Training Program", subjectCode:'NST02', section:'' },
  { id:'cc_cpe_020', dept:'cpe', year:'2nd Year', semester:'1st Semester', courseCode:'GEC01', subjectName:"The Life and Works of Rizal", lecUnits:3, labUnits:0, units:3, courseName:"The Life and Works of Rizal", subjectCode:'GEC01', section:'' },
  { id:'cc_cpe_021', dept:'cpe', year:'2nd Year', semester:'1st Semester', courseCode:'GEC09', subjectName:"Ethics", lecUnits:3, labUnits:0, units:3, courseName:"Ethics", subjectCode:'GEC09', section:'' },
  { id:'cc_cpe_022', dept:'cpe', year:'2nd Year', semester:'1st Semester', courseCode:'EEN01', subjectName:"Fundamentals of Electrical Circuits", lecUnits:3, labUnits:0, units:3, courseName:"Fundamentals of Electrical Circuits", subjectCode:'EEN01', section:'' },
  { id:'cc_cpe_023', dept:'cpe', year:'2nd Year', semester:'1st Semester', courseCode:'EEN01L', subjectName:"Fundamentals of Electrical Circuits (Lab)", lecUnits:0, labUnits:1, units:1, courseName:"Fundamentals of Electrical Circuits (Lab)", subjectCode:'EEN01L', section:'' },
  { id:'cc_cpe_024', dept:'cpe', year:'2nd Year', semester:'1st Semester', courseCode:'CAD01', subjectName:"Computer-Aided Drafting", lecUnits:0, labUnits:1, units:1, courseName:"Computer-Aided Drafting", subjectCode:'CAD01', section:'' },
  { id:'cc_cpe_025', dept:'cpe', year:'2nd Year', semester:'1st Semester', courseCode:'MAT07', subjectName:"Differential Equations", lecUnits:3, labUnits:0, units:3, courseName:"Differential Equations", subjectCode:'MAT07', section:'' },
  { id:'cc_cpe_026', dept:'cpe', year:'2nd Year', semester:'1st Semester', courseCode:'CPE01', subjectName:"Discrete Mathematics", lecUnits:3, labUnits:0, units:3, courseName:"Discrete Mathematics", subjectCode:'CPE01', section:'' },
  { id:'cc_cpe_027', dept:'cpe', year:'2nd Year', semester:'1st Semester', courseCode:'CPE02', subjectName:"Programming and Logic Design", lecUnits:0, labUnits:2, units:2, courseName:"Programming and Logic Design", subjectCode:'CPE02', section:'' },
  { id:'cc_cpe_028', dept:'cpe', year:'2nd Year', semester:'1st Semester', courseCode:'CPE03', subjectName:"Database Management System", lecUnits:2, labUnits:1, units:3, courseName:"Database Management System", subjectCode:'CPE03', section:'' },
  { id:'cc_cpe_029', dept:'cpe', year:'2nd Year', semester:'1st Semester', courseCode:'PEO03', subjectName:"Individual/Dual Games/Sports", lecUnits:2, labUnits:0, units:2, courseName:"Individual/Dual Games/Sports", subjectCode:'PEO03', section:'' },
  { id:'cc_cpe_030', dept:'cpe', year:'2nd Year', semester:'2nd Semester', courseCode:'GEC07', subjectName:"Art Appreciation", lecUnits:3, labUnits:0, units:3, courseName:"Art Appreciation", subjectCode:'GEC07', section:'' },
  { id:'cc_cpe_031', dept:'cpe', year:'2nd Year', semester:'2nd Semester', courseCode:'GEC13', subjectName:"Literature of the Philippines", lecUnits:3, labUnits:0, units:3, courseName:"Literature of the Philippines", subjectCode:'GEC13', section:'' },
  { id:'cc_cpe_032', dept:'cpe', year:'2nd Year', semester:'2nd Semester', courseCode:'MAT08', subjectName:"Engineering Data Analysis", lecUnits:3, labUnits:0, units:3, courseName:"Engineering Data Analysis", subjectCode:'MAT08', section:'' },
  { id:'cc_cpe_033', dept:'cpe', year:'2nd Year', semester:'2nd Semester', courseCode:'ECE01', subjectName:"Fundamentals of Electronic Circuits", lecUnits:3, labUnits:0, units:3, courseName:"Fundamentals of Electronic Circuits", subjectCode:'ECE01', section:'' },
  { id:'cc_cpe_034', dept:'cpe', year:'2nd Year', semester:'2nd Semester', courseCode:'ECE01L', subjectName:"Fundamentals of Electronic Circuits (Lab)", lecUnits:0, labUnits:1, units:1, courseName:"Fundamentals of Electronic Circuits (Lab)", subjectCode:'ECE01L', section:'' },
  { id:'cc_cpe_035', dept:'cpe', year:'2nd Year', semester:'2nd Semester', courseCode:'CPE04', subjectName:"Numerical Methods", lecUnits:3, labUnits:0, units:3, courseName:"Numerical Methods", subjectCode:'CPE04', section:'' },
  { id:'cc_cpe_036', dept:'cpe', year:'2nd Year', semester:'2nd Semester', courseCode:'CPE05', subjectName:"Object-Oriented Programming", lecUnits:0, labUnits:2, units:2, courseName:"Object-Oriented Programming", subjectCode:'CPE05', section:'' },
  { id:'cc_cpe_037', dept:'cpe', year:'2nd Year', semester:'2nd Semester', courseCode:'CPE06', subjectName:"On-Line Technologies", lecUnits:2, labUnits:1, units:3, courseName:"On-Line Technologies", subjectCode:'CPE06', section:'' },
  { id:'cc_cpe_038', dept:'cpe', year:'2nd Year', semester:'2nd Semester', courseCode:'PEO04', subjectName:"Team Sports/Games", lecUnits:2, labUnits:0, units:2, courseName:"Team Sports/Games", subjectCode:'PEO04', section:'' },
  { id:'cc_cpe_039', dept:'cpe', year:'3rd Year', semester:'1st Semester', courseCode:'CPE07', subjectName:"Logic Circuits and Design", lecUnits:3, labUnits:0, units:3, courseName:"Logic Circuits and Design", subjectCode:'CPE07', section:'' },
  { id:'cc_cpe_040', dept:'cpe', year:'3rd Year', semester:'1st Semester', courseCode:'CPE07L', subjectName:"Logic Circuits and Design (Lab)", lecUnits:0, labUnits:1, units:1, courseName:"Logic Circuits and Design (Lab)", subjectCode:'CPE07L', section:'' },
  { id:'cc_cpe_041', dept:'cpe', year:'3rd Year', semester:'1st Semester', courseCode:'CPE08', subjectName:"Computer Engineering Drafting & Design", lecUnits:0, labUnits:1, units:1, courseName:"Computer Engineering Drafting & Design", subjectCode:'CPE08', section:'' },
  { id:'cc_cpe_042', dept:'cpe', year:'3rd Year', semester:'1st Semester', courseCode:'CPE09', subjectName:"Introduction to HDL", lecUnits:0, labUnits:1, units:1, courseName:"Introduction to HDL", subjectCode:'CPE09', section:'' },
  { id:'cc_cpe_043', dept:'cpe', year:'3rd Year', semester:'1st Semester', courseCode:'CPE10', subjectName:"Fundamentals of Mixed Signals & Sensors", lecUnits:3, labUnits:0, units:3, courseName:"Fundamentals of Mixed Signals & Sensors", subjectCode:'CPE10', section:'' },
  { id:'cc_cpe_044', dept:'cpe', year:'3rd Year', semester:'1st Semester', courseCode:'CPE11', subjectName:"Feedback and Control Systems", lecUnits:3, labUnits:0, units:3, courseName:"Feedback and Control Systems", subjectCode:'CPE11', section:'' },
  { id:'cc_cpe_045', dept:'cpe', year:'3rd Year', semester:'1st Semester', courseCode:'CPE12', subjectName:"Data and Digital Communications", lecUnits:3, labUnits:0, units:3, courseName:"Data and Digital Communications", subjectCode:'CPE12', section:'' },
  { id:'cc_cpe_046', dept:'cpe', year:'3rd Year', semester:'1st Semester', courseCode:'CPE13', subjectName:"Data Structure and Algorithms", lecUnits:0, labUnits:2, units:2, courseName:"Data Structure and Algorithms", subjectCode:'CPE13', section:'' },
  { id:'cc_cpe_047', dept:'cpe', year:'3rd Year', semester:'1st Semester', courseCode:'CPE14', subjectName:"Basic Occupational Health and Safety", lecUnits:3, labUnits:0, units:3, courseName:"Basic Occupational Health and Safety", subjectCode:'CPE14', section:'' },
  { id:'cc_cpe_048', dept:'cpe', year:'3rd Year', semester:'1st Semester', courseCode:'CPE15', subjectName:"Cognate/Professional Course 1", lecUnits:2, labUnits:1, units:3, courseName:"Cognate/Professional Course 1", subjectCode:'CPE15', section:'' },
  { id:'cc_cpe_049', dept:'cpe', year:'3rd Year', semester:'2nd Semester', courseCode:'BES01', subjectName:"Engineering Economics", lecUnits:3, labUnits:0, units:3, courseName:"Engineering Economics", subjectCode:'BES01', section:'' },
  { id:'cc_cpe_050', dept:'cpe', year:'3rd Year', semester:'2nd Semester', courseCode:'CPE16', subjectName:"Computer Networks & Security", lecUnits:3, labUnits:0, units:3, courseName:"Computer Networks & Security", subjectCode:'CPE16', section:'' },
  { id:'cc_cpe_051', dept:'cpe', year:'3rd Year', semester:'2nd Semester', courseCode:'CPE16L', subjectName:"Computer Networks & Security (Lab)", lecUnits:0, labUnits:1, units:1, courseName:"Computer Networks & Security (Lab)", subjectCode:'CPE16L', section:'' },
  { id:'cc_cpe_052', dept:'cpe', year:'3rd Year', semester:'2nd Semester', courseCode:'CPE17', subjectName:"Operating Systems", lecUnits:2, labUnits:1, units:3, courseName:"Operating Systems", subjectCode:'CPE17', section:'' },
  { id:'cc_cpe_053', dept:'cpe', year:'3rd Year', semester:'2nd Semester', courseCode:'CPE18', subjectName:"Software Design", lecUnits:3, labUnits:0, units:3, courseName:"Software Design", subjectCode:'CPE18', section:'' },
  { id:'cc_cpe_054', dept:'cpe', year:'3rd Year', semester:'2nd Semester', courseCode:'CPE18L', subjectName:"Software Design (Lab)", lecUnits:0, labUnits:1, units:1, courseName:"Software Design (Lab)", subjectCode:'CPE18L', section:'' },
  { id:'cc_cpe_055', dept:'cpe', year:'3rd Year', semester:'2nd Semester', courseCode:'CPE19', subjectName:"Microprocessors", lecUnits:3, labUnits:0, units:3, courseName:"Microprocessors", subjectCode:'CPE19', section:'' },
  { id:'cc_cpe_056', dept:'cpe', year:'3rd Year', semester:'2nd Semester', courseCode:'CPE19L', subjectName:"Microprocessors (Lab)", lecUnits:0, labUnits:1, units:1, courseName:"Microprocessors (Lab)", subjectCode:'CPE19L', section:'' },
  { id:'cc_cpe_057', dept:'cpe', year:'3rd Year', semester:'2nd Semester', courseCode:'CPE20', subjectName:"Methods and Research", lecUnits:2, labUnits:0, units:2, courseName:"Methods and Research", subjectCode:'CPE20', section:'' },
  { id:'cc_cpe_058', dept:'cpe', year:'3rd Year', semester:'2nd Semester', courseCode:'CPE21', subjectName:"Cognate/Professional Course 2", lecUnits:2, labUnits:1, units:3, courseName:"Cognate/Professional Course 2", subjectCode:'CPE21', section:'' },
  { id:'cc_cpe_059', dept:'cpe', year:'4th Year', semester:'1st Semester', courseCode:'BSE04', subjectName:"Technopreneurship 101", lecUnits:3, labUnits:0, units:3, courseName:"Technopreneurship 101", subjectCode:'BSE04', section:'' },
  { id:'cc_cpe_060', dept:'cpe', year:'4th Year', semester:'1st Semester', courseCode:'CPE22', subjectName:"Digital Signal Processing", lecUnits:3, labUnits:0, units:3, courseName:"Digital Signal Processing", subjectCode:'CPE22', section:'' },
  { id:'cc_cpe_061', dept:'cpe', year:'4th Year', semester:'1st Semester', courseCode:'CPE22L', subjectName:"Digital Signal Processing (Lab)", lecUnits:0, labUnits:1, units:1, courseName:"Digital Signal Processing (Lab)", subjectCode:'CPE22L', section:'' },
  { id:'cc_cpe_062', dept:'cpe', year:'4th Year', semester:'1st Semester', courseCode:'CPE23', subjectName:"Computer Architecture & Organization", lecUnits:3, labUnits:0, units:3, courseName:"Computer Architecture & Organization", subjectCode:'CPE23', section:'' },
  { id:'cc_cpe_063', dept:'cpe', year:'4th Year', semester:'1st Semester', courseCode:'CPE23L', subjectName:"Computer Architecture & Organization (Lab)", lecUnits:0, labUnits:1, units:1, courseName:"Computer Architecture & Organization (Lab)", subjectCode:'CPE23L', section:'' },
  { id:'cc_cpe_064', dept:'cpe', year:'4th Year', semester:'1st Semester', courseCode:'CPE24', subjectName:"Embedded Systems", lecUnits:3, labUnits:0, units:3, courseName:"Embedded Systems", subjectCode:'CPE24', section:'' },
  { id:'cc_cpe_065', dept:'cpe', year:'4th Year', semester:'1st Semester', courseCode:'CPE24L', subjectName:"Embedded Systems (Lab)", lecUnits:0, labUnits:1, units:1, courseName:"Embedded Systems (Lab)", subjectCode:'CPE24L', section:'' },
  { id:'cc_cpe_066', dept:'cpe', year:'4th Year', semester:'1st Semester', courseCode:'CPE25', subjectName:"CpE Practice and Design 1", lecUnits:0, labUnits:1, units:1, courseName:"CpE Practice and Design 1", subjectCode:'CPE25', section:'' },
  { id:'cc_cpe_067', dept:'cpe', year:'4th Year', semester:'1st Semester', courseCode:'CPE26', subjectName:"CpE Laws and Professional Practice", lecUnits:2, labUnits:0, units:2, courseName:"CpE Laws and Professional Practice", subjectCode:'CPE26', section:'' },
  { id:'cc_cpe_068', dept:'cpe', year:'4th Year', semester:'1st Semester', courseCode:'CPE27', subjectName:"Emerging Technologies in CpE", lecUnits:3, labUnits:0, units:3, courseName:"Emerging Technologies in CpE", subjectCode:'CPE27', section:'' },
  { id:'cc_cpe_069', dept:'cpe', year:'4th Year', semester:'1st Semester', courseCode:'CPE28', subjectName:"Cognate/Professional Course 3", lecUnits:2, labUnits:1, units:3, courseName:"Cognate/Professional Course 3", subjectCode:'CPE28', section:'' },
  { id:'cc_cpe_070', dept:'cpe', year:'4th Year', semester:'2nd Semester', courseCode:'CPE29', subjectName:"Seminars and Field Trips", lecUnits:0, labUnits:1, units:1, courseName:"Seminars and Field Trips", subjectCode:'CPE29', section:'' },
  { id:'cc_cpe_071', dept:'cpe', year:'4th Year', semester:'2nd Semester', courseCode:'CPE30', subjectName:"CpE Practice and Design 2", lecUnits:0, labUnits:2, units:2, courseName:"CpE Practice and Design 2", subjectCode:'CPE30', section:'' },
  { id:'cc_cpe_072', dept:'cpe', year:'4th Year', semester:'2nd Semester', courseCode:'OJT', subjectName:"On-The-Job Training (240hrs)", lecUnits:3, labUnits:0, units:3, courseName:"On-The-Job Training (240hrs)", subjectCode:'OJT', section:'' },
];
