// data.js
// Core data includes content imported from "CEN Updated Sched - Sheet1.pdf"
// (rooms, faculty roster, 1st-year curriculum samples, section labels). Weekly
// time slots were not in the PDF — SCHEDULES below are illustrative placements.

const DEPARTMENTS = [
  { id:'ie', code:'IE', name:'Industrial Engineering', chair:'Engr. Lynnevel R. Amparo' },
  { id:'cpe', code:'CPE', name:'Computer Engineering', chair:'Engr. Julie Ann Susa-Gili' },
  { id:'ce', code:'CE', name:'Civil Engineering', chair:'Engr. John Christopher D. Tayoto' },
  { id:'ee', code:'EE', name:'Electrical Engineering', chair:'Engr. Maurino N. Abuel' },
  { id:'me', code:'ME', name:'Mechanical Engineering', chair:'Engr. Ronnel S. Nombrefia' },
  { id:'ece', code:'ECE', name:'Electronics Engineering', chair:'Engr. Pitz Gerald G. Lagrazon' },
];

// Rooms from PDF "CLASSROM (Lab & Lec)" table — columns IE, CPE, CE, EE, ME, ECE
const ROOMS = [
  { id:'ie_mdhp303', name:'MDHP 303', type:'classroom', dept:'ie' },
  { id:'cpe_302', name:'MDHP 302', type:'classroom', dept:'cpe' },
  { id:'ce_mdhp103', name:'MDHP 103', type:'classroom', dept:'ce' },
  { id:'ee_mdhp209', name:'MDHP 209', type:'classroom', dept:'ee' },
  { id:'me_mhdp102', name:'MHDP 102', type:'classroom', dept:'me' },
  { id:'ece_mhdp201', name:'MHDP 201', type:'classroom', dept:'ece' },
  { id:'ie_mdhp305', name:'MDHP 305', type:'classroom', dept:'ie' },
  { id:'cpe_101', name:'MDHP 101', type:'classroom', dept:'cpe' },
  { id:'ce_mdhp105', name:'MDHP 105', type:'classroom', dept:'ce' },
  { id:'ee_mdhp211', name:'MDHP 211', type:'classroom', dept:'ee' },
  { id:'me_mhdp108', name:'MHDP 108', type:'classroom', dept:'me' },
  { id:'ece_mhdp203', name:'MHDP 203', type:'classroom', dept:'ece' },
  { id:'ie_mdhp307', name:'MDHP 307', type:'classroom', dept:'ie' },
  { id:'cpe_207', name:'MDHP 207', type:'classroom', dept:'cpe' },
  { id:'ce_mdhp107', name:'MDHP 107', type:'classroom', dept:'ce' },
  { id:'ee_mdhp301', name:'MDHP 301', type:'classroom', dept:'ee' },
  { id:'me_mhdp114', name:'MHDP 114', type:'classroom', dept:'me' },
  { id:'ece_mhdp205', name:'MHDP 205', type:'classroom', dept:'ece' },
  { id:'lab_ie_a', name:'IE LAB A', type:'laboratory', dept:'ie' },
  { id:'lab_cpe_a', name:'CPE LAB A', type:'laboratory', dept:'cpe' },
  { id:'ce_mdhp111', name:'MDHP 111 (LAB)', type:'laboratory', dept:'ce' },
  { id:'ce_mdhp306', name:'MDHP 306', type:'classroom', dept:'ce' },
  { id:'me_mdhp_melab', name:'MDHP ME LAB', type:'laboratory', dept:'me' },
  { id:'ece_mhdp207', name:'MHDP 207', type:'classroom', dept:'ece' },
  { id:'lab_ie_b', name:'IE LAB B', type:'laboratory', dept:'ie' },
  { id:'lab_cpe_b', name:'CPE LAB B', type:'laboratory', dept:'cpe' },
  { id:'ce_drwng', name:'DRWNG ROOM', type:'classroom', dept:'ce' },
  { id:'lab_ee_a', name:'EE LAB A', type:'laboratory', dept:'ee' },
  { id:'me_new_melab', name:'NEW ME LAB', type:'laboratory', dept:'me' },
  { id:'ece_mhdp209', name:'MHDP 209', type:'classroom', dept:'ece' },
  { id:'ee_lab_b', name:'EE LAB B', type:'laboratory', dept:'ee' },
  { id:'ce_draw_rm', name:'DRAWING ROOM', type:'classroom', dept:'ce' },
  { id:'me_draw_rm', name:'DRAWING ROOM', type:'classroom', dept:'me' },
  { id:'ece_fm_lab', name:'FM LAB', type:'laboratory', dept:'ece' },
  { id:'ee_lab_c', name:'EE LAB C', type:'laboratory', dept:'ee' },
  { id:'ece_elex_lab', name:'ELEX LAB', type:'laboratory', dept:'ece' },
  { id:'r101', name:'Room 101', type:'classroom', dept:'ie' },
  { id:'r201', name:'Room 201', type:'classroom', dept:'ee' },
  { id:'r301', name:'Room 301', type:'classroom', dept:'ce' },
  { id:'r401', name:'Room 401', type:'classroom', dept:'me' },
  { id:'r501', name:'Room 501', type:'classroom', dept:'ece' },
  { id:'r601', name:'Room 601', type:'classroom', dept:'cpe' },
  { id:'r602', name:'Room 602', type:'classroom', dept:'cpe' },
  { id:'lab_ee_b', name:'EE Lab B', type:'laboratory', dept:'ee' },
];

// Faculty from PDF (rows under PROFESSORS); column order IE, CPE, CE, EE, ME, ECE
const PROFESSORS_DATA = [
  { id:'p_ie_1', name:'Dr. Maria Corazon B. Abejo', short:'M. Abejo', dept:'ie', active:true },
  { id:'p_cpe_1', name:'Engr. Mandonna D. Castro', short:'M. Castro', dept:'cpe', active:true },
  { id:'p_ce_1', name:'Engr. Winda S. Ellaga', short:'W. Ellaga', dept:'ce', active:true },
  { id:'p_ee_1', name:'Engr. Maurino N. Abuel', short:'M. Abuel', dept:'ee', active:true },
  { id:'p_me_1', name:'Engr. Gilbert R. Esquillio', short:'G. Esquillio', dept:'me', active:true },
  { id:'p_ece_1', name:'Dr. Pitz Gerald G. Lagrazon', short:'P. Lagrazon', dept:'ece', active:true },
  { id:'p_ie_2', name:'Engr. Lynnevel R. Amparo', short:'L. Amparo', dept:'ie', active:true },
  { id:'p_cpe_2', name:'Engr. Carla May C. Ceribo', short:'C. Ceribo', dept:'cpe', active:true },
  { id:'p_ce_2', name:'Engr. Jamaica C. Saliendra', short:'J. Saliendra', dept:'ce', active:true },
  { id:'p_ee_2', name:'Engr. Aubee Mahusay-Ecleo', short:'A. Ecleo', dept:'ee', active:true },
  { id:'p_me_2', name:'Engr. Ronnel S. Nombrefia', short:'R. Nombrefia', dept:'me', active:true },
  { id:'p_ece_2', name:'Engr. John Vistor Adel T. Liwag', short:'J. Liwag', dept:'ece', active:true },
  { id:'p_ie_3', name:'Dr. Maria Rossana D. De Veluz', short:'M. De Veluz', dept:'ie', active:true },
  { id:'p_cpe_3', name:'Engr. Julie Ann S. Gili', short:'J. Gili', dept:'cpe', active:true },
  { id:'p_ce_3', name:'Engr. John Christopher D. Tayoto', short:'J. Tayoto', dept:'ce', active:true },
  { id:'p_ee_3', name:'Engr. John V. Ella', short:'J. Ella', dept:'ee', active:true },
  { id:'p_me_3', name:'Engr. Oscar D. Villaverde', short:'O. Villaverde', dept:'me', active:true },
  { id:'p_ece_3', name:'Engr. Zoren P. Mabunga', short:'Z. Mabunga', dept:'ece', active:true },
  { id:'p_ie_4', name:'Engr. Maribelle A. Gaytano', short:'M. Gaytano', dept:'ie', active:true },
  { id:'p_cpe_4', name:'Dr. Renato R. Maaliw III', short:'R. Maaliw', dept:'cpe', active:true },
  { id:'p_ce_4', name:'Ar. Aivan Benedict Q. Ella', short:'A. Ella', dept:'ce', active:true },
  { id:'p_ee_4', name:'Dr. Efren D. Villaverde', short:'E. Villaverde', dept:'ee', active:true },
  { id:'p_me_4', name:'Engr. Dan Mark C. Cabriga', short:'D. Cabriga', dept:'me', active:true },
  { id:'p_ece_4', name:'Engr. Maurine C. Panergio', short:'M. Panergio', dept:'ece', active:true },
  { id:'p_ie_5', name:'Engr. Cresencia R. Jarabese', short:'C. Jarabese', dept:'ie', active:true },
  { id:'p_cpe_5', name:'Engr. John Harvey Alva', short:'J. Alva', dept:'cpe', active:true },
  { id:'p_ce_5', name:'Engr. Jane Coleen R. Lingatong', short:'J. Lingatong', dept:'ce', active:true },
  { id:'p_ee_5', name:'Engr. Rizandy J. Arroyo', short:'R. Arroyo', dept:'ee', active:true },
  { id:'p_me_5', name:'Engr. Ramon Ace Vitasa', short:'R. Vitasa', dept:'me', active:true },
  { id:'p_ece_5', name:'Engr. Renante D. Abuyan', short:'R. Abuyan', dept:'ece', active:true },
  { id:'p_ie_6', name:'Engr. Reglelyn N. Menchero', short:'R. Menchero', dept:'ie', active:true },
  { id:'p_cpe_6', name:'Engr. Maria Nieves D. Elarco', short:'M. Elarco', dept:'cpe', active:true },
  { id:'p_ce_6', name:'Engr. Delia O. Evangelista', short:'D. Evangelista', dept:'ce', active:true },
  { id:'p_ee_6', name:'Engr. Meller P. Gonzales', short:'M. Gonzales', dept:'ee', active:true },
  { id:'p_me_6', name:'Engr. Dona B. Bueque', short:'D. Bueque', dept:'me', active:true },
  { id:'p_ece_6', name:'Engr. Renante D. Abuyan', short:'R. Abuyan', dept:'ece', active:true },
  { id:'p_ie_7', name:'Engr. Ernest Paul Y. Sison', short:'E. Sison', dept:'ie', active:true },
  { id:'p_cpe_7', name:'Engr. Jose Yulo Manzanero', short:'J. Manzanero', dept:'cpe', active:true },
  { id:'p_ce_7', name:'Engr. Jerome Ignacio', short:'J. Ignacio', dept:'ce', active:true },
  { id:'p_ee_7', name:'Engr. Romeo O. Maroto', short:'R. Maroto', dept:'ee', active:true },
  { id:'p_me_7', name:'Engr. Maureen E. Roaza', short:'M. Roaza', dept:'me', active:true },
  { id:'p_ece_7', name:'Engr. Joel Anthony L. Sevilla', short:'J. Sevilla', dept:'ece', active:true },
  { id:'p_ie_8', name:'Engr. Omar Irish S. Maravilla', short:'O. Maravilla', dept:'ie', active:true },
  { id:'p_cpe_8', name:'Engr. Marcelito P. Oblea Jr.', short:'M. Oblea', dept:'cpe', active:true },
  { id:'p_ce_8', name:'Engr. Jerome D. Ignacio', short:'J. Ignacio', dept:'ce', active:true },
  { id:'p_ee_8', name:'Engr. Marjun C. Macriola', short:'M. Macriola', dept:'ee', active:true },
  { id:'p_me_8', name:'Engr. Dean Adrian L. Nombrefia', short:'D. Nombrefia', dept:'me', active:true },
  { id:'p_cpe_9', name:'Engr. Mark Daries Q. Sardea', short:'M. Sardea', dept:'cpe', active:true },
  { id:'p_ee_9', name:'Engr. Anthony L. Reigo', short:'A. Reigo', dept:'ee', active:true },
  { id:'p_ie_9', name:'Engr. Jerwin V. Obmerga', short:'J. Obmerga', dept:'ie', active:true },
  { id:'p_cpe_10', name:'Engr. Conrado E. Quinalayo', short:'C. Quinalayo', dept:'cpe', active:true },
  { id:'p_ee_10', name:'Engr. Ralph Monsour Z. Delima', short:'R. Delima', dept:'ee', active:true },
  { id:'p_ie_10', name:'Engr. Leonard Allen R. Pavino', short:'L. Pavino', dept:'ie', active:true },
  { id:'p_cpe_11', name:'Engr. Maria Nieves D. Elarco', short:'M. Elarco', dept:'cpe', active:true },
];

// 1st Year 1st Sem courses from PDF (per department column)
const SUBJECTS_DATA = [
  { id:'s_ie_chm01a', code:'CHM01a', name:'Chemistry for Engineers', dept:'ie', units:3, sem:'Y1S1', active:true },
  { id:'s_cpe_gec04', code:'GEC04', name:'The Contemporary World', dept:'cpe', units:3, sem:'Y1S1', active:true },
  { id:'s_ce_chm01a', code:'CHM01A', name:'Chemistry for Engineers', dept:'ce', units:3, sem:'Y1S1', active:true },
  { id:'s_ee_gec04', code:'GEC04', name:'The Contemporary World', dept:'ee', units:3, sem:'Y1S1', active:true },
  { id:'s_me_coe01', code:'COE01', name:'Mechanical Engineering Orientation', dept:'me', units:2, sem:'Y1S1', active:true },
  { id:'s_ece_gec04', code:'GEC04', name:'The Contemporary World', dept:'ece', units:3, sem:'Y1S1', active:true },
  { id:'s_ie_chm01al', code:'CHM01aL', name:'Chemistry for Engineers (Lab)', dept:'ie', units:1, sem:'Y1S1', active:true },
  { id:'s_cpe_gec05', code:'GEC05', name:'Mathematics in the Modern World', dept:'cpe', units:3, sem:'Y1S1', active:true },
  { id:'s_ce_chm01al', code:'CHM01AL', name:'Chemistry for Engineers (Lab)', dept:'ce', units:1, sem:'Y1S1', active:true },
  { id:'s_ee_gec05', code:'GEC05', name:'Mathematics in the Modern World', dept:'ee', units:3, sem:'Y1S1', active:true },
  { id:'s_me_gec05', code:'GEC05', name:'Mathematics in the Modern World', dept:'me', units:3, sem:'Y1S1', active:true },
  { id:'s_ece_gec05', code:'GEC05', name:'Mathematics in the Modern World', dept:'ece', units:3, sem:'Y1S1', active:true },
  { id:'s_ie_gec02', code:'GEC02', name:'Understanding the Self', dept:'ie', units:3, sem:'Y1S1', active:true },
  { id:'s_cpe_gec08', code:'GEC08', name:'Science, Technology and Society', dept:'cpe', units:3, sem:'Y1S1', active:true },
  { id:'s_ce_cve00', code:'CVE00', name:'Civil Engineering Orientation', dept:'ce', units:2, sem:'Y1S1', active:true },
  { id:'s_ee_gec08', code:'GEC08', name:'Science, Technology & Society', dept:'ee', units:3, sem:'Y1S1', active:true },
  { id:'s_me_chm01a', code:'CHM01a', name:'Chemistry for Engineers', dept:'me', units:3, sem:'Y1S1', active:true },
  { id:'s_ece_gec08', code:'GEC08', name:'Science, Technology and Society', dept:'ece', units:3, sem:'Y1S1', active:true },
  { id:'s_ie_gec03', code:'GEC03', name:'Readings in the Philippine History', dept:'ie', units:3, sem:'Y1S1', active:true },
  { id:'s_cpe_gec10', code:'GEC10', name:'Kontekswalisadong Komunikasyon sa Filipino', dept:'cpe', units:3, sem:'Y1S1', active:true },
  { id:'s_ce_cve01', code:'CVE01', name:'Engineering Drawings and Plans', dept:'ce', units:2, sem:'Y1S1', active:true },
  { id:'s_ee_gec10', code:'GEC10', name:'Kontekswalisadong Komunikasyon sa Filipino', dept:'ee', units:3, sem:'Y1S1', active:true },
  { id:'s_me_chm01al', code:'CHM01aL', name:'Chemistry for Engineers (Lab)', dept:'me', units:1, sem:'Y1S1', active:true },
  { id:'s_ece_mat04', code:'MAT04', name:'Calculus 1 (Differential Calculus)', dept:'ece', units:3, sem:'Y1S1', active:true },
  { id:'s_ie_gec05b', code:'GEC05', name:'Mathematics in the Modern World', dept:'ie', units:3, sem:'Y1S1', active:true },
  { id:'s_cpe_mat04', code:'MAT04', name:'Calculus 1 (Differential)', dept:'cpe', units:3, sem:'Y1S1', active:true },
  { id:'s_ce_gec04', code:'GEC04', name:'The Contemporary World', dept:'ce', units:3, sem:'Y1S1', active:true },
  { id:'s_ee_chm01', code:'CHM01', name:'Chemistry for Engineers', dept:'ee', units:3, sem:'Y1S1', active:true },
  { id:'s_me_mat04', code:'MAT04', name:'Calculus 1 (Differential)', dept:'me', units:3, sem:'Y1S1', active:true },
  { id:'s_ece_chm01a', code:'CHM01a', name:'Chemistry for Engineers', dept:'ece', units:3, sem:'Y1S1', active:true },
  { id:'s_ie_gec10', code:'GEC10', name:'Kontekswalisadong Komunikasyon sa Filipino', dept:'ie', units:3, sem:'Y1S1', active:true },
  { id:'s_cpe_chm01a', code:'CHM01A', name:'Chemistry for Engineers', dept:'cpe', units:3, sem:'Y1S1', active:true },
  { id:'s_ce_gec05', code:'GEC05', name:'Mathematics in the Modern World', dept:'ce', units:3, sem:'Y1S1', active:true },
  { id:'s_ee_chm01al', code:'CHM01aL', name:'Chemistry for Engineers (Lab)', dept:'ee', units:1, sem:'Y1S1', active:true },
  { id:'s_me_gec02', code:'GEC02', name:'Understanding the Self', dept:'me', units:3, sem:'Y1S1', active:true },
  { id:'s_ece_chm01al', code:'CHM01aL', name:'Chemistry for Engineers (Lab)', dept:'ece', units:1, sem:'Y1S1', active:true },
  { id:'s_ie_mat04', code:'MAT04', name:'Calculus 1 (Differential Calculus)', dept:'ie', units:3, sem:'Y1S1', active:true },
  { id:'s_cpe_chm01al', code:'CHM01AL', name:'Chemistry for Engineers (Lab)', dept:'cpe', units:1, sem:'Y1S1', active:true },
  { id:'s_ce_gec08', code:'GEC08', name:'Science, Technology and Society', dept:'ce', units:3, sem:'Y1S1', active:true },
  { id:'s_ee_mat01', code:'MAT01', name:'Calculus 1 (Differential)', dept:'ee', units:3, sem:'Y1S1', active:true },
  { id:'s_me_drw01', code:'DRW01', name:'Engineering Drawing', dept:'me', units:2, sem:'Y1S1', active:true },
  { id:'s_ece_cad01', code:'CAD01', name:'Computer Aided Drafting', dept:'ece', units:2, sem:'Y1S1', active:true },
  { id:'s_ie_peo01', code:'PEO01', name:'Physical Fitness', dept:'ie', units:2, sem:'Y1S1', active:true },
  { id:'s_cpe_coe01b', code:'COE01', name:'Computer Engineering as a Discipline', dept:'cpe', units:2, sem:'Y1S1', active:true },
  { id:'s_ce_mat04', code:'MAT04', name:'Calculus 1 (Differential Calculus)', dept:'ce', units:3, sem:'Y1S1', active:true },
  { id:'s_ee_coe01', code:'COE01', name:'Engineering Orientation', dept:'ee', units:2, sem:'Y1S1', active:true },
  { id:'s_me_gec07', code:'GEC07', name:'Art Appreciation', dept:'me', units:3, sem:'Y1S1', active:true },
  { id:'s_ece_peo01', code:'PEO01', name:'Physical Fitness', dept:'ece', units:2, sem:'Y1S1', active:true },
  { id:'s_ie_nst01', code:'NST01', name:'ROTC', dept:'ie', units:3, sem:'Y1S1', active:true },
  { id:'s_cpe_peo01', code:'PEO01', name:'Physical Fitness', dept:'cpe', units:2, sem:'Y1S1', active:true },
  { id:'s_ce_nst01', code:'NST01', name:'ROTC', dept:'ce', units:3, sem:'Y1S1', active:true },
  { id:'s_ee_nst01', code:'NST01', name:'National Service Training Program 1', dept:'ee', units:3, sem:'Y1S1', active:true },
  { id:'s_me_gec03', code:'GEC03', name:'Mathematics in the Modern World', dept:'me', units:3, sem:'Y1S1', active:true },
  { id:'s_ece_nst01', code:'NST01', name:'National Service Training Program 1', dept:'ece', units:3, sem:'Y1S1', active:true },
  { id:'s_cpe_nst01', code:'NST01', name:'National Service Training Program 1', dept:'cpe', units:3, sem:'Y1S1', active:true },
  { id:'s_me_nst01', code:'NST01', name:'National Service Training Program 1', dept:'me', units:3, sem:'Y1S1', active:true },
  { id:'s_me_path01', code:'PATHFIT01', name:'Movement Skill Training', dept:'me', units:2, sem:'Y1S1', active:true },
  // Legacy ids for app flows / requests
  { id:'s1', code:'IE101', name:'Engineering Management', dept:'ie', units:3, sem:'1st', active:true },
  { id:'s2', code:'IE102', name:'Operations Research', dept:'ie', units:3, sem:'1st', active:true },
  { id:'s3', code:'EEN01', name:'Basic Electrical Engineering', dept:'ee', units:3, sem:'1st', active:true },
  { id:'s4', code:'EEN01L', name:'Basic EE Laboratory', dept:'ee', units:1, sem:'1st', active:true },
  { id:'s5', code:'CE101', name:'Engineering Mechanics', dept:'ce', units:3, sem:'1st', active:true },
  { id:'s6', code:'ME101', name:'Thermodynamics', dept:'me', units:3, sem:'1st', active:true },
  { id:'s7', code:'ECE101', name:'Electronics 1', dept:'ece', units:3, sem:'1st', active:true },
  { id:'s8', code:'CPE101', name:'Computer Architecture', dept:'cpe', units:3, sem:'1st', active:true },
  { id:'s9', code:'CPE102', name:'Data Structures', dept:'cpe', units:3, sem:'1st', active:true },
];

// PDF has no weekly matrix — sample placements using PDF section names & rooms
const SCHEDULES = [
  { id:'sch1', subjectId:'s_ee_chm01', professorId:'p_ee_1', roomId:'ee_mdhp209', dept:'ee', section:'BSEE I GI', days:['Monday','Wednesday'], timeStart:'07:30', timeEnd:'09:00', color:'blue', setLabel:null, labLabel:null },
  { id:'sch2', subjectId:'s_cpe_mat04', professorId:'p_cpe_3', roomId:'cpe_302', dept:'cpe', section:'BSCPE I GE', days:['Tuesday','Thursday'], timeStart:'09:00', timeEnd:'10:30', color:'blue', setLabel:null, labLabel:null },
  { id:'sch3', subjectId:'s_cpe_gec05', professorId:'p_cpe_2', roomId:'r602', dept:'cpe', section:'BSCPE I GE', days:['Monday','Wednesday'], timeStart:'10:30', timeEnd:'12:00', color:'blue', setLabel:null, labLabel:null },
  { id:'sch4', subjectId:'s_ie_mat04', professorId:'p_ie_2', roomId:'ie_mdhp303', dept:'ie', section:'BSIE IGK', days:['Monday','Wednesday','Friday'], timeStart:'07:30', timeEnd:'08:30', color:'green', setLabel:null, labLabel:null },
  { id:'sch5', subjectId:'s_ce_cve01', professorId:'p_ce_3', roomId:'ce_mdhp103', dept:'ce', section:'BSCE I GA', days:['Tuesday','Thursday'], timeStart:'07:30', timeEnd:'09:00', color:'blue', setLabel:null, labLabel:null },
  { id:'sch6', subjectId:'s_me_coe01', professorId:'p_me_2', roomId:'me_mhdp102', dept:'me', section:'BSME I GM', days:['Monday','Wednesday'], timeStart:'13:00', timeEnd:'14:30', color:'blue', setLabel:null, labLabel:null },
  { id:'sch7', subjectId:'s_ece_mat04', professorId:'p_ece_1', roomId:'ece_mhdp201', dept:'ece', section:'BSECE I GG', days:['Tuesday','Thursday'], timeStart:'14:30', timeEnd:'16:00', color:'blue', setLabel:null, labLabel:null },
  { id:'sch8', subjectId:'s_ie_chm01al', professorId:'p_ie_1', roomId:'lab_ie_a', dept:'ie', section:'BSIE IGK-A', days:['Friday'], timeStart:'09:00', timeEnd:'12:00', color:'purple', setLabel:null, labLabel:null },
];

/** Sample borrow requests: scoped by dept so each chairperson sees Incoming (toDept) / Outgoing (fromDept) on the Requests page. */
const REQUESTS = [
  { id:'req1', fromDept:'cpe', toDept:'ee', roomId:'lab_ee_b', subjectId:'s9', section:'BSCPE I GF', professorId:'p_cpe_2', days:['Wednesday'], timeStart:'15:00', timeEnd:'17:00', reason:'Lab fully booked', status:'pending', created:'2026-01-15' },
  { id:'req2', fromDept:'ee', toDept:'ie', roomId:'ie_mdhp305', subjectId:'s3', section:'BSEE I GI', professorId:'p_ee_2', days:['Monday'], timeStart:'10:30', timeEnd:'12:00', reason:'Exam block — need larger room', status:'pending', created:'2026-01-12' },
  { id:'req3', fromDept:'me', toDept:'ce', roomId:'ce_mdhp107', subjectId:'s6', section:'BSME I GM', professorId:'p_me_2', days:['Tuesday','Thursday'], timeStart:'13:00', timeEnd:'14:30', reason:'Dept workshop', status:'pending', created:'2026-01-10' },
  { id:'req4', fromDept:'cpe', toDept:'ece', roomId:'ece_mhdp203', subjectId:'s8', section:'BSCPE I GE', professorId:'p_cpe_3', days:['Friday'], timeStart:'09:00', timeEnd:'10:30', reason:'', status:'approved', created:'2026-01-08' },
  { id:'req5', fromDept:'ie', toDept:'me', roomId:'me_mhdp108', subjectId:'s1', section:'BSIE IGK', professorId:'p_ie_2', days:['Wednesday'], timeStart:'07:30', timeEnd:'09:00', reason:'Joint lecture', status:'pending', created:'2026-01-14' },
  { id:'req6', fromDept:'ce', toDept:'ece', roomId:'ece_mhdp205', subjectId:'s5', section:'BSCE I GA', professorId:'p_ce_3', days:['Monday'], timeStart:'14:30', timeEnd:'16:00', reason:'', status:'pending', created:'2026-01-11' },
  { id:'req7', fromDept:'cpe', toDept:'ee', roomId:'ee_mdhp211', subjectId:'s_cpe_mat04', section:'BSCPE I GE', professorId:'p_cpe_3', days:['Thursday'], timeStart:'16:00', timeEnd:'17:30', reason:'Make-up class', status:'pending', created:'2026-01-16' },
  { id:'req8', fromDept:'ece', toDept:'ie', roomId:'lab_ie_a', subjectId:'s7', section:'BSECE I GG', professorId:'p_ece_2', days:['Tuesday'], timeStart:'13:30', timeEnd:'16:00', reason:'Lab equipment', status:'declined', created:'2026-01-05' },
  { id:'req9', fromDept:'ee', toDept:'cpe', roomId:'lab_cpe_b', subjectId:'s4', section:'BSEE I GI', professorId:'p_ee_3', days:['Monday','Wednesday'], timeStart:'15:00', timeEnd:'16:30', reason:'Circuits lab overflow', status:'pending', created:'2026-01-17' },
  /** Prototype incoming (IE chair demo login: ie.chair@plm.edu.ph) — ensures a visible Requests notification. */
  { id:'req_proto_demo', fromDept:'me', toDept:'ie', roomId:'ie_mdhp307', subjectId:'s6', section:'BSME I GM', professorId:'p_me_3', days:['Friday'], timeStart:'10:30', timeEnd:'12:00', reason:'[Demo prototype] Borrow IE classroom for cross-dept activity', status:'pending', created:'2026-04-18' },
];

const DAYS = ['Monday','Tuesday','Wednesday','Thursday','Friday'];
const timeSlots = ['07:30','08:00','08:30','09:00','09:30','10:00','10:30','11:00','11:30','12:00','12:30','13:00','13:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00','17:30','18:00','18:30','19:00','19:30'];

// Sample section labels for schedule / request dropdowns (merged with sections already on timetables)
const SECTION_SAMPLES_BY_DEPT = {
  ie: ['BSIE - IIGK', 'BSIE - 1AGH', 'BSIE IGK', 'BSIE - IIKH'],
  cpe: ['BSCPE - I GE', 'BSCPE I GF', 'BSCPE I GE', 'BSCPE - II GH'],
  ce: ['BSCE - I GA', 'BSCE I GA', 'BSCE - II GB'],
  ee: ['BSEE - I GI', 'BSEE I GI', 'BSEE - II GJ'],
  me: ['BSME - I GM', 'BSME I GM', 'BSME - II GN'],
  ece: ['BSECE - I GG', 'BSECE I GG', 'BSECE - II GK'],
};

// Admin curriculum catalog (separate from subject master list used for scheduling links)
const CURRICULUM_DATA = [
  { id:'cc_me_1', dept:'me', courseCode:'ME 100', courseName:'Mechanical Engineering Orientation Block', subjectCode:'COE01', subjectName:'Mechanical Engineering Orientation', units:2, section:'BSME I GM' },
  { id:'cc_ie_1', dept:'ie', courseCode:'IE 100', courseName:'Industrial Engineering Orientation', subjectCode:'IE101', subjectName:'Engineering Management', units:3, section:'BSIE - IIGK' },
  { id:'cc_cpe_1', dept:'cpe', courseCode:'CPE 100', courseName:'Computer Engineering Fundamentals', subjectCode:'CPE101', subjectName:'Computer Architecture', units:3, section:'BSCPE - I GE' },
];
